//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.common;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PermissibleUseAssertionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PermissibleUseAssertionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DPPA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="None"/>
 *               &lt;enumeration value="Fraud Prevention"/>
 *               &lt;enumeration value="Insurance"/>
 *               &lt;enumeration value="Government Agency"/>
 *               &lt;enumeration value="Government Contractor"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GLBA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="None"/>
 *               &lt;enumeration value="Fraud Prevention"/>
 *               &lt;enumeration value="Beneficial Interest"/>
 *               &lt;enumeration value="Enforce Transaction by Consumer"/>
 *               &lt;enumeration value="Institutional Risk"/>
 *               &lt;enumeration value="Consumer Dispute"/>
 *               &lt;enumeration value="Federal State Local Laws"/>
 *               &lt;enumeration value="Law Enforcement State Insurance Agencies"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PermissibleUseAssertionType", propOrder = {
    "dppa",
    "glba"
})
public class PermissibleUseAssertionType {

    @XmlElement(name = "DPPA")
    protected String dppa;
    @XmlElement(name = "GLBA")
    protected String glba;

    /**
     * Gets the value of the dppa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDPPA() {
        return dppa;
    }

    /**
     * Sets the value of the dppa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDPPA(String value) {
        this.dppa = value;
    }

    /**
     * Gets the value of the glba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLBA() {
        return glba;
    }

    /**
     * Sets the value of the glba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLBA(String value) {
        this.glba = value;
    }

}
