//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.acxiom.schemas.v201110.us.idod.common.ResponseAddressType;


/**
 * <p>Java class for AddressType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.acxiom.com/v201110/us/idod/common}ResponseAddressType">
 *       &lt;sequence>
 *         &lt;element name="RestrictedUseCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="SourceCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="AddressStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateEnded" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateLastVerified" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateReported" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DropPointIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DwellingUnitSizeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LengthOfResidence" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="OccOrder" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="OwnOrRent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressPhone" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}IndividualAddressPhoneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PostDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreDirection" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondaryNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SpecialAddressTypeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Street" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StreetSuffix" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitDesignator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressType", propOrder = {
    "restrictedUseCode",
    "sourceCode",
    "addressStatus",
    "dateEnded",
    "dateLastVerified",
    "dateReported",
    "dropPointIndicator",
    "dwellingUnitSizeFlag",
    "lengthOfResidence",
    "occOrder",
    "ownOrRent",
    "addressPhone",
    "postDirection",
    "preDirection",
    "primaryNumber",
    "secondaryNumber",
    "specialAddressTypeFlag",
    "street",
    "streetSuffix",
    "unitDesignator"
})
public class AddressType
    extends ResponseAddressType
{

    @XmlElement(name = "RestrictedUseCode")
    protected Long restrictedUseCode;
    @XmlElement(name = "SourceCode")
    protected Long sourceCode;
    @XmlElement(name = "AddressStatus")
    protected String addressStatus;
    @XmlElement(name = "DateEnded")
    protected String dateEnded;
    @XmlElement(name = "DateLastVerified")
    protected String dateLastVerified;
    @XmlElement(name = "DateReported")
    protected String dateReported;
    @XmlElement(name = "DropPointIndicator")
    protected String dropPointIndicator;
    @XmlElement(name = "DwellingUnitSizeFlag")
    protected String dwellingUnitSizeFlag;
    @XmlElement(name = "LengthOfResidence")
    protected Long lengthOfResidence;
    @XmlElement(name = "OccOrder")
    protected Long occOrder;
    @XmlElement(name = "OwnOrRent")
    protected String ownOrRent;
    @XmlElement(name = "AddressPhone")
    protected List<IndividualAddressPhoneType> addressPhone;
    @XmlElement(name = "PostDirection")
    protected String postDirection;
    @XmlElement(name = "PreDirection")
    protected String preDirection;
    @XmlElement(name = "PrimaryNumber")
    protected String primaryNumber;
    @XmlElement(name = "SecondaryNumber")
    protected String secondaryNumber;
    @XmlElement(name = "SpecialAddressTypeFlag")
    protected String specialAddressTypeFlag;
    @XmlElement(name = "Street")
    protected String street;
    @XmlElement(name = "StreetSuffix")
    protected String streetSuffix;
    @XmlElement(name = "UnitDesignator")
    protected String unitDesignator;

    /**
     * Gets the value of the restrictedUseCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getRestrictedUseCode() {
        return restrictedUseCode;
    }

    /**
     * Sets the value of the restrictedUseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setRestrictedUseCode(Long value) {
        this.restrictedUseCode = value;
    }

    /**
     * Gets the value of the sourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSourceCode() {
        return sourceCode;
    }

    /**
     * Sets the value of the sourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSourceCode(Long value) {
        this.sourceCode = value;
    }

    /**
     * Gets the value of the addressStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStatus() {
        return addressStatus;
    }

    /**
     * Sets the value of the addressStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStatus(String value) {
        this.addressStatus = value;
    }

    /**
     * Gets the value of the dateEnded property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateEnded() {
        return dateEnded;
    }

    /**
     * Sets the value of the dateEnded property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateEnded(String value) {
        this.dateEnded = value;
    }

    /**
     * Gets the value of the dateLastVerified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateLastVerified() {
        return dateLastVerified;
    }

    /**
     * Sets the value of the dateLastVerified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateLastVerified(String value) {
        this.dateLastVerified = value;
    }

    /**
     * Gets the value of the dateReported property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateReported() {
        return dateReported;
    }

    /**
     * Sets the value of the dateReported property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateReported(String value) {
        this.dateReported = value;
    }

    /**
     * Gets the value of the dropPointIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDropPointIndicator() {
        return dropPointIndicator;
    }

    /**
     * Sets the value of the dropPointIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDropPointIndicator(String value) {
        this.dropPointIndicator = value;
    }

    /**
     * Gets the value of the dwellingUnitSizeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDwellingUnitSizeFlag() {
        return dwellingUnitSizeFlag;
    }

    /**
     * Sets the value of the dwellingUnitSizeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDwellingUnitSizeFlag(String value) {
        this.dwellingUnitSizeFlag = value;
    }

    /**
     * Gets the value of the lengthOfResidence property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLengthOfResidence() {
        return lengthOfResidence;
    }

    /**
     * Sets the value of the lengthOfResidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLengthOfResidence(Long value) {
        this.lengthOfResidence = value;
    }

    /**
     * Gets the value of the occOrder property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOccOrder() {
        return occOrder;
    }

    /**
     * Sets the value of the occOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOccOrder(Long value) {
        this.occOrder = value;
    }

    /**
     * Gets the value of the ownOrRent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnOrRent() {
        return ownOrRent;
    }

    /**
     * Sets the value of the ownOrRent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnOrRent(String value) {
        this.ownOrRent = value;
    }

    /**
     * Gets the value of the addressPhone property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the addressPhone property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddressPhone().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndividualAddressPhoneType }
     * 
     * 
     */
    public List<IndividualAddressPhoneType> getAddressPhone() {
        if (addressPhone == null) {
            addressPhone = new ArrayList<IndividualAddressPhoneType>();
        }
        return this.addressPhone;
    }

    /**
     * Gets the value of the postDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostDirection() {
        return postDirection;
    }

    /**
     * Sets the value of the postDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostDirection(String value) {
        this.postDirection = value;
    }

    /**
     * Gets the value of the preDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreDirection() {
        return preDirection;
    }

    /**
     * Sets the value of the preDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreDirection(String value) {
        this.preDirection = value;
    }

    /**
     * Gets the value of the primaryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryNumber() {
        return primaryNumber;
    }

    /**
     * Sets the value of the primaryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryNumber(String value) {
        this.primaryNumber = value;
    }

    /**
     * Gets the value of the secondaryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryNumber() {
        return secondaryNumber;
    }

    /**
     * Sets the value of the secondaryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryNumber(String value) {
        this.secondaryNumber = value;
    }

    /**
     * Gets the value of the specialAddressTypeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialAddressTypeFlag() {
        return specialAddressTypeFlag;
    }

    /**
     * Sets the value of the specialAddressTypeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialAddressTypeFlag(String value) {
        this.specialAddressTypeFlag = value;
    }

    /**
     * Gets the value of the street property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreet() {
        return street;
    }

    /**
     * Sets the value of the street property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreet(String value) {
        this.street = value;
    }

    /**
     * Gets the value of the streetSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStreetSuffix() {
        return streetSuffix;
    }

    /**
     * Sets the value of the streetSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStreetSuffix(String value) {
        this.streetSuffix = value;
    }

    /**
     * Gets the value of the unitDesignator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitDesignator() {
        return unitDesignator;
    }

    /**
     * Sets the value of the unitDesignator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitDesignator(String value) {
        this.unitDesignator = value;
    }

}
