//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeceasedInfoDetailType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeceasedInfoDetailType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DateOfDeath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeceasedConfidenceRestrictedUseCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DeceasedConfidenceSourceCode" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DeceasedConfidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeceasedInfoDetailType", propOrder = {
    "dateOfDeath",
    "deceasedConfidenceRestrictedUseCode",
    "deceasedConfidenceSourceCode",
    "deceasedConfidence"
})
public class DeceasedInfoDetailType {

    @XmlElement(name = "DateOfDeath")
    protected String dateOfDeath;
    @XmlElement(name = "DeceasedConfidenceRestrictedUseCode")
    protected Long deceasedConfidenceRestrictedUseCode;
    @XmlElement(name = "DeceasedConfidenceSourceCode")
    protected Long deceasedConfidenceSourceCode;
    @XmlElement(name = "DeceasedConfidence")
    protected String deceasedConfidence;

    /**
     * Gets the value of the dateOfDeath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateOfDeath() {
        return dateOfDeath;
    }

    /**
     * Sets the value of the dateOfDeath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateOfDeath(String value) {
        this.dateOfDeath = value;
    }

    /**
     * Gets the value of the deceasedConfidenceRestrictedUseCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeceasedConfidenceRestrictedUseCode() {
        return deceasedConfidenceRestrictedUseCode;
    }

    /**
     * Sets the value of the deceasedConfidenceRestrictedUseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeceasedConfidenceRestrictedUseCode(Long value) {
        this.deceasedConfidenceRestrictedUseCode = value;
    }

    /**
     * Gets the value of the deceasedConfidenceSourceCode property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDeceasedConfidenceSourceCode() {
        return deceasedConfidenceSourceCode;
    }

    /**
     * Sets the value of the deceasedConfidenceSourceCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDeceasedConfidenceSourceCode(Long value) {
        this.deceasedConfidenceSourceCode = value;
    }

    /**
     * Gets the value of the deceasedConfidence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeceasedConfidence() {
        return deceasedConfidence;
    }

    /**
     * Sets the value of the deceasedConfidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeceasedConfidence(String value) {
        this.deceasedConfidence = value;
    }

}
