//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndividualAddressPhoneType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualAddressPhoneType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}PhoneType">
 *       &lt;sequence>
 *         &lt;element name="IndividualAddressPhoneRank" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualAddressPhoneType", propOrder = {
    "individualAddressPhoneRank"
})
public class IndividualAddressPhoneType
    extends PhoneType
{

    @XmlElement(name = "IndividualAddressPhoneRank")
    protected Long individualAddressPhoneRank;

    /**
     * Gets the value of the individualAddressPhoneRank property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getIndividualAddressPhoneRank() {
        return individualAddressPhoneRank;
    }

    /**
     * Sets the value of the individualAddressPhoneRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setIndividualAddressPhoneRank(Long value) {
        this.individualAddressPhoneRank = value;
    }

}
