//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndividualType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Address" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}AddressType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Alias" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}AliasOutputType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Deceased" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}DeceasedInfoType" minOccurs="0"/>
 *         &lt;element name="DOB" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}DOBInfoType" minOccurs="0"/>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *         &lt;element name="FraudVictimIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MatchReasonCode" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}NameInfoType" minOccurs="0"/>
 *         &lt;element name="Phones" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}PhonesType" minOccurs="0"/>
 *         &lt;element name="PrimaryEntityIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="VerificationFlags" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}VerificationFlagsType" minOccurs="0"/>
 *         &lt;element name="SourceIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SSN" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}SSNInfoType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="WatchListIndicator" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="WatchListMatch" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}WatchListMatchType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualType", propOrder = {
    "address",
    "alias",
    "deceased",
    "dob",
    "individualId",
    "fraudVictimIndicator",
    "gender",
    "matchReasonCode",
    "name",
    "phones",
    "primaryEntityIndicator",
    "verificationFlags",
    "sourceIndicator",
    "ssn",
    "watchListIndicator",
    "watchListMatch"
})
public class IndividualType {

    @XmlElement(name = "Address")
    protected List<AddressType> address;
    @XmlElement(name = "Alias")
    protected List<AliasOutputType> alias;
    @XmlElement(name = "Deceased")
    protected DeceasedInfoType deceased;
    @XmlElement(name = "DOB")
    protected DOBInfoType dob;
    @XmlElement(name = "IndividualId")
    protected String individualId;
    @XmlElement(name = "FraudVictimIndicator")
    protected String fraudVictimIndicator;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "MatchReasonCode")
    protected List<String> matchReasonCode;
    @XmlElement(name = "Name")
    protected NameInfoType name;
    @XmlElement(name = "Phones")
    protected PhonesType phones;
    @XmlElement(name = "PrimaryEntityIndicator")
    protected Boolean primaryEntityIndicator;
    @XmlElement(name = "VerificationFlags")
    protected VerificationFlagsType verificationFlags;
    @XmlElement(name = "SourceIndicator")
    protected String sourceIndicator;
    @XmlElement(name = "SSN")
    protected List<SSNInfoType> ssn;
    @XmlElement(name = "WatchListIndicator")
    protected Boolean watchListIndicator;
    @XmlElement(name = "WatchListMatch")
    protected WatchListMatchType watchListMatch;

    /**
     * Gets the value of the address property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the address property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AddressType }
     * 
     * 
     */
    public List<AddressType> getAddress() {
        if (address == null) {
            address = new ArrayList<AddressType>();
        }
        return this.address;
    }

    /**
     * Gets the value of the alias property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the alias property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAlias().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AliasOutputType }
     * 
     * 
     */
    public List<AliasOutputType> getAlias() {
        if (alias == null) {
            alias = new ArrayList<AliasOutputType>();
        }
        return this.alias;
    }

    /**
     * Gets the value of the deceased property.
     * 
     * @return
     *     possible object is
     *     {@link DeceasedInfoType }
     *     
     */
    public DeceasedInfoType getDeceased() {
        return deceased;
    }

    /**
     * Sets the value of the deceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeceasedInfoType }
     *     
     */
    public void setDeceased(DeceasedInfoType value) {
        this.deceased = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link DOBInfoType }
     *     
     */
    public DOBInfoType getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOBInfoType }
     *     
     */
    public void setDOB(DOBInfoType value) {
        this.dob = value;
    }

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

    /**
     * Gets the value of the fraudVictimIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudVictimIndicator() {
        return fraudVictimIndicator;
    }

    /**
     * Sets the value of the fraudVictimIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudVictimIndicator(String value) {
        this.fraudVictimIndicator = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the matchReasonCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matchReasonCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatchReasonCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMatchReasonCode() {
        if (matchReasonCode == null) {
            matchReasonCode = new ArrayList<String>();
        }
        return this.matchReasonCode;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NameInfoType }
     *     
     */
    public NameInfoType getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameInfoType }
     *     
     */
    public void setName(NameInfoType value) {
        this.name = value;
    }

    /**
     * Gets the value of the phones property.
     * 
     * @return
     *     possible object is
     *     {@link PhonesType }
     *     
     */
    public PhonesType getPhones() {
        return phones;
    }

    /**
     * Sets the value of the phones property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhonesType }
     *     
     */
    public void setPhones(PhonesType value) {
        this.phones = value;
    }

    /**
     * Gets the value of the primaryEntityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPrimaryEntityIndicator() {
        return primaryEntityIndicator;
    }

    /**
     * Sets the value of the primaryEntityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPrimaryEntityIndicator(Boolean value) {
        this.primaryEntityIndicator = value;
    }

    /**
     * Gets the value of the verificationFlags property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationFlagsType }
     *     
     */
    public VerificationFlagsType getVerificationFlags() {
        return verificationFlags;
    }

    /**
     * Sets the value of the verificationFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationFlagsType }
     *     
     */
    public void setVerificationFlags(VerificationFlagsType value) {
        this.verificationFlags = value;
    }

    /**
     * Gets the value of the sourceIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceIndicator() {
        return sourceIndicator;
    }

    /**
     * Sets the value of the sourceIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceIndicator(String value) {
        this.sourceIndicator = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ssn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSSN().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SSNInfoType }
     * 
     * 
     */
    public List<SSNInfoType> getSSN() {
        if (ssn == null) {
            ssn = new ArrayList<SSNInfoType>();
        }
        return this.ssn;
    }

    /**
     * Gets the value of the watchListIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isWatchListIndicator() {
        return watchListIndicator;
    }

    /**
     * Sets the value of the watchListIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setWatchListIndicator(Boolean value) {
        this.watchListIndicator = value;
    }

    /**
     * Gets the value of the watchListMatch property.
     * 
     * @return
     *     possible object is
     *     {@link WatchListMatchType }
     *     
     */
    public WatchListMatchType getWatchListMatch() {
        return watchListMatch;
    }

    /**
     * Sets the value of the watchListMatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link WatchListMatchType }
     *     
     */
    public void setWatchListMatch(WatchListMatchType value) {
        this.watchListMatch = value;
    }

}
