//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InputFormatFaultsListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputFormatFaultsListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="InputFormatFault" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/response}InputFormatFaultType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputFormatFaultsListType", propOrder = {
    "inputFormatFault"
})
public class InputFormatFaultsListType {

    @XmlElement(name = "InputFormatFault")
    protected List<InputFormatFaultType> inputFormatFault;

    /**
     * Gets the value of the inputFormatFault property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputFormatFault property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputFormatFault().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputFormatFaultType }
     * 
     * 
     */
    public List<InputFormatFaultType> getInputFormatFault() {
        if (inputFormatFault == null) {
            inputFormatFault = new ArrayList<InputFormatFaultType>();
        }
        return this.inputFormatFault;
    }

}
