//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.request;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.acxiom.schemas.v201110.us.idod.findpeople.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://schemas.acxiom.com/v201110/us/idod/findpeople/request", "Request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.acxiom.schemas.v201110.us.idod.findpeople.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link InputListType }
     * 
     */
    public InputListType createInputListType() {
        return new InputListType();
    }

    /**
     * Create an instance of {@link DataRequestOptionsType }
     * 
     */
    public DataRequestOptionsType createDataRequestOptionsType() {
        return new DataRequestOptionsType();
    }

    /**
     * Create an instance of {@link InputType }
     * 
     */
    public InputType createInputType() {
        return new InputType();
    }

    /**
     * Create an instance of {@link AliasOptionsType }
     * 
     */
    public AliasOptionsType createAliasOptionsType() {
        return new AliasOptionsType();
    }

    /**
     * Create an instance of {@link ProcessOptionsType }
     * 
     */
    public ProcessOptionsType createProcessOptionsType() {
        return new ProcessOptionsType();
    }

    /**
     * Create an instance of {@link PhoneOptionsType }
     * 
     */
    public PhoneOptionsType createPhoneOptionsType() {
        return new PhoneOptionsType();
    }

    /**
     * Create an instance of {@link AnalysisOptionsType }
     * 
     */
    public AnalysisOptionsType createAnalysisOptionsType() {
        return new AnalysisOptionsType();
    }

    /**
     * Create an instance of {@link NameAddressOptionsType }
     * 
     */
    public NameAddressOptionsType createNameAddressOptionsType() {
        return new NameAddressOptionsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.acxiom.com/v201110/us/idod/findpeople/request", name = "Request")
    public JAXBElement<RequestType> createRequest(RequestType value) {
        return new JAXBElement<RequestType>(_Request_QNAME, RequestType.class, null, value);
    }

}
