//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.findpeople.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProcessOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnalysisOptions" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/request}AnalysisOptionsType" minOccurs="0"/>
 *         &lt;element name="DataRequestOptions" type="{http://schemas.acxiom.com/v201110/us/idod/findpeople/request}DataRequestOptionsType"/>
 *         &lt;element name="ReturnCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProcessOptionsType", propOrder = {
    "analysisOptions",
    "dataRequestOptions",
    "returnCount"
})
public class ProcessOptionsType {

    @XmlElement(name = "AnalysisOptions")
    protected AnalysisOptionsType analysisOptions;
    @XmlElement(name = "DataRequestOptions", required = true)
    protected DataRequestOptionsType dataRequestOptions;
    @XmlElement(name = "ReturnCount", defaultValue = "25")
    protected int returnCount;

    /**
     * Gets the value of the analysisOptions property.
     * 
     * @return
     *     possible object is
     *     {@link AnalysisOptionsType }
     *     
     */
    public AnalysisOptionsType getAnalysisOptions() {
        return analysisOptions;
    }

    /**
     * Sets the value of the analysisOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalysisOptionsType }
     *     
     */
    public void setAnalysisOptions(AnalysisOptionsType value) {
        this.analysisOptions = value;
    }

    /**
     * Gets the value of the dataRequestOptions property.
     * 
     * @return
     *     possible object is
     *     {@link DataRequestOptionsType }
     *     
     */
    public DataRequestOptionsType getDataRequestOptions() {
        return dataRequestOptions;
    }

    /**
     * Sets the value of the dataRequestOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataRequestOptionsType }
     *     
     */
    public void setDataRequestOptions(DataRequestOptionsType value) {
        this.dataRequestOptions = value;
    }

    /**
     * Gets the value of the returnCount property.
     * 
     */
    public int getReturnCount() {
        return returnCount;
    }

    /**
     * Sets the value of the returnCount property.
     * 
     */
    public void setReturnCount(int value) {
        this.returnCount = value;
    }

}
