//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ComprehensiveNameAddressInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ComprehensiveNameAddressInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AssociativeData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PeopleAssociativeData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ContactData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PeopleContactData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NameAddressData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}ComprehensiveNameAddressPropertyInfo" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ComprehensiveNameAddressInfo", propOrder = {
    "associativeData",
    "contactData",
    "nameAddressData"
})
public class ComprehensiveNameAddressInfo {

    @XmlElement(name = "AssociativeData")
    protected List<PeopleAssociativeData> associativeData;
    @XmlElement(name = "ContactData")
    protected List<PeopleContactData> contactData;
    @XmlElement(name = "NameAddressData")
    protected List<ComprehensiveNameAddressPropertyInfo> nameAddressData;

    /**
     * Gets the value of the associativeData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associativeData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociativeData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeopleAssociativeData }
     * 
     * 
     */
    public List<PeopleAssociativeData> getAssociativeData() {
        if (associativeData == null) {
            associativeData = new ArrayList<PeopleAssociativeData>();
        }
        return this.associativeData;
    }

    /**
     * Gets the value of the contactData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeopleContactData }
     * 
     * 
     */
    public List<PeopleContactData> getContactData() {
        if (contactData == null) {
            contactData = new ArrayList<PeopleContactData>();
        }
        return this.contactData;
    }

    /**
     * Gets the value of the nameAddressData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAddressData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAddressData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ComprehensiveNameAddressPropertyInfo }
     * 
     * 
     */
    public List<ComprehensiveNameAddressPropertyInfo> getNameAddressData() {
        if (nameAddressData == null) {
            nameAddressData = new ArrayList<ComprehensiveNameAddressPropertyInfo>();
        }
        return this.nameAddressData;
    }

}
