//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.acxiom.schemas.v201110.us.idod.common.RestrictedUseType;


/**
 * <p>Java class for ConcealedWeaponsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConcealedWeaponsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ConcealedWeapon" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}ConcealedWeaponType" minOccurs="0"/>
 *         &lt;element name="RestrictedUseInfo" type="{http://schemas.acxiom.com/v201110/us/idod/common}RestrictedUseType" minOccurs="0"/>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConcealedWeaponsType", propOrder = {
    "concealedWeapon",
    "restrictedUseInfo",
    "individualId"
})
public class ConcealedWeaponsType {

    @XmlElement(name = "ConcealedWeapon")
    protected ConcealedWeaponType concealedWeapon;
    @XmlElement(name = "RestrictedUseInfo")
    protected RestrictedUseType restrictedUseInfo;
    @XmlElement(name = "IndividualId")
    protected String individualId;

    /**
     * Gets the value of the concealedWeapon property.
     * 
     * @return
     *     possible object is
     *     {@link ConcealedWeaponType }
     *     
     */
    public ConcealedWeaponType getConcealedWeapon() {
        return concealedWeapon;
    }

    /**
     * Sets the value of the concealedWeapon property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConcealedWeaponType }
     *     
     */
    public void setConcealedWeapon(ConcealedWeaponType value) {
        this.concealedWeapon = value;
    }

    /**
     * Gets the value of the restrictedUseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedUseType }
     *     
     */
    public RestrictedUseType getRestrictedUseInfo() {
        return restrictedUseInfo;
    }

    /**
     * Sets the value of the restrictedUseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedUseType }
     *     
     */
    public void setRestrictedUseInfo(RestrictedUseType value) {
        this.restrictedUseInfo = value;
    }

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

}
