//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EmployersType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EmployersType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Employer" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}EmployerType" minOccurs="0"/>
 *         &lt;element name="RestrictedUseInfo" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}EmployerRestrictedUseType" minOccurs="0"/>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EmployersType", propOrder = {
    "employer",
    "restrictedUseInfo",
    "individualId"
})
public class EmployersType {

    @XmlElement(name = "Employer")
    protected EmployerType employer;
    @XmlElement(name = "RestrictedUseInfo")
    protected EmployerRestrictedUseType restrictedUseInfo;
    @XmlElement(name = "IndividualId")
    protected String individualId;

    /**
     * Gets the value of the employer property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerType }
     *     
     */
    public EmployerType getEmployer() {
        return employer;
    }

    /**
     * Sets the value of the employer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerType }
     *     
     */
    public void setEmployer(EmployerType value) {
        this.employer = value;
    }

    /**
     * Gets the value of the restrictedUseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EmployerRestrictedUseType }
     *     
     */
    public EmployerRestrictedUseType getRestrictedUseInfo() {
        return restrictedUseInfo;
    }

    /**
     * Sets the value of the restrictedUseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EmployerRestrictedUseType }
     *     
     */
    public void setRestrictedUseInfo(EmployerRestrictedUseType value) {
        this.restrictedUseInfo = value;
    }

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

}
