//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HigherEducationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HigherEducationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcademicClassification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Commuter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompileYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FieldOfStudy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OnCampus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Origination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SchoolName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HigherEducationType", propOrder = {
    "academicClassification",
    "commuter",
    "compileYear",
    "fieldOfStudy",
    "onCampus",
    "origination",
    "schoolName"
})
public class HigherEducationType {

    @XmlElement(name = "AcademicClassification")
    protected String academicClassification;
    @XmlElement(name = "Commuter")
    protected String commuter;
    @XmlElement(name = "CompileYear")
    protected String compileYear;
    @XmlElement(name = "FieldOfStudy")
    protected String fieldOfStudy;
    @XmlElement(name = "OnCampus")
    protected String onCampus;
    @XmlElement(name = "Origination")
    protected String origination;
    @XmlElement(name = "SchoolName")
    protected String schoolName;

    /**
     * Gets the value of the academicClassification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcademicClassification() {
        return academicClassification;
    }

    /**
     * Sets the value of the academicClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcademicClassification(String value) {
        this.academicClassification = value;
    }

    /**
     * Gets the value of the commuter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCommuter() {
        return commuter;
    }

    /**
     * Sets the value of the commuter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCommuter(String value) {
        this.commuter = value;
    }

    /**
     * Gets the value of the compileYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompileYear() {
        return compileYear;
    }

    /**
     * Sets the value of the compileYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompileYear(String value) {
        this.compileYear = value;
    }

    /**
     * Gets the value of the fieldOfStudy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldOfStudy() {
        return fieldOfStudy;
    }

    /**
     * Sets the value of the fieldOfStudy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldOfStudy(String value) {
        this.fieldOfStudy = value;
    }

    /**
     * Gets the value of the onCampus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnCampus() {
        return onCampus;
    }

    /**
     * Sets the value of the onCampus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnCampus(String value) {
        this.onCampus = value;
    }

    /**
     * Gets the value of the origination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigination() {
        return origination;
    }

    /**
     * Sets the value of the origination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigination(String value) {
        this.origination = value;
    }

    /**
     * Gets the value of the schoolName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * Sets the value of the schoolName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchoolName(String value) {
        this.schoolName = value;
    }

}
