//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchResultsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchResultsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SearchID" type="{http://schemas.acxiom.com/v201110/us/idod/common}SearchIDType" minOccurs="0"/>
 *         &lt;element name="TransactionID" type="{http://schemas.acxiom.com/v201110/us/idod/common}TransactionIDType" minOccurs="0"/>
 *         &lt;element name="MatchResult" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}MatchResultType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchResultsType", propOrder = {
    "searchID",
    "transactionID",
    "matchResult"
})
public class MatchResultsType {

    @XmlElement(name = "SearchID")
    protected String searchID;
    @XmlElement(name = "TransactionID")
    protected String transactionID;
    @XmlElement(name = "MatchResult")
    protected MatchResultType matchResult;

    /**
     * Gets the value of the searchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchID() {
        return searchID;
    }

    /**
     * Sets the value of the searchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchID(String value) {
        this.searchID = value;
    }

    /**
     * Gets the value of the transactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionID() {
        return transactionID;
    }

    /**
     * Sets the value of the transactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionID(String value) {
        this.transactionID = value;
    }

    /**
     * Gets the value of the matchResult property.
     * 
     * @return
     *     possible object is
     *     {@link MatchResultType }
     *     
     */
    public MatchResultType getMatchResult() {
        return matchResult;
    }

    /**
     * Sets the value of the matchResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchResultType }
     *     
     */
    public void setMatchResult(MatchResultType value) {
        this.matchResult = value;
    }

}
