//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Addresses" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}ComprehensiveNameAddressInfo" minOccurs="0"/>
 *         &lt;element name="Aircrafts" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}AircraftsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Aliases" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}AliasesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Associates" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}AssociateRelative" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ConcealedWeapons" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}ConcealedWeaponsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CorporateAssociationsAndEmployment" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}EmployersType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DeaRegistrations" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}DEARegistrationsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="DriversLicenses" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}DriversLicensesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HigherEducations" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}HigherEducationsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="HuntingFishing" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}HuntersType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="InternetDomains" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}DomainsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Neighbors" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborOutput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Phones" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PeoplePhoneData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Pilots" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PilotsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PremiumVehicles" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PremiumVehiclesOutput" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProfessionalLicenses" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}ProfessionalLicensesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RecreationalVehicles" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}RecreationalVehiclesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Relatives" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}AssociateRelative" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SocialSecurityNumbers" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PeopleSsnData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Vehicles" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}VehiclesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Boats" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}BoatsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Voters" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}VotersType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchResultType", propOrder = {
    "addresses",
    "aircrafts",
    "aliases",
    "associates",
    "concealedWeapons",
    "corporateAssociationsAndEmployment",
    "deaRegistrations",
    "driversLicenses",
    "higherEducations",
    "huntingFishing",
    "internetDomains",
    "neighbors",
    "phones",
    "pilots",
    "premiumVehicles",
    "professionalLicenses",
    "recreationalVehicles",
    "relatives",
    "socialSecurityNumbers",
    "vehicles",
    "boats",
    "voters"
})
public class MatchResultType {

    @XmlElement(name = "Addresses")
    protected ComprehensiveNameAddressInfo addresses;
    @XmlElement(name = "Aircrafts")
    protected List<AircraftsType> aircrafts;
    @XmlElement(name = "Aliases")
    protected List<AliasesType> aliases;
    @XmlElement(name = "Associates")
    protected List<AssociateRelative> associates;
    @XmlElement(name = "ConcealedWeapons")
    protected List<ConcealedWeaponsType> concealedWeapons;
    @XmlElement(name = "CorporateAssociationsAndEmployment")
    protected List<EmployersType> corporateAssociationsAndEmployment;
    @XmlElement(name = "DeaRegistrations")
    protected List<DEARegistrationsType> deaRegistrations;
    @XmlElement(name = "DriversLicenses")
    protected List<DriversLicensesType> driversLicenses;
    @XmlElement(name = "HigherEducations")
    protected List<HigherEducationsType> higherEducations;
    @XmlElement(name = "HuntingFishing")
    protected List<HuntersType> huntingFishing;
    @XmlElement(name = "InternetDomains")
    protected List<DomainsType> internetDomains;
    @XmlElement(name = "Neighbors")
    protected List<NeighborOutput> neighbors;
    @XmlElement(name = "Phones")
    protected List<PeoplePhoneData> phones;
    @XmlElement(name = "Pilots")
    protected List<PilotsType> pilots;
    @XmlElement(name = "PremiumVehicles")
    protected List<PremiumVehiclesOutput> premiumVehicles;
    @XmlElement(name = "ProfessionalLicenses")
    protected List<ProfessionalLicensesType> professionalLicenses;
    @XmlElement(name = "RecreationalVehicles")
    protected List<RecreationalVehiclesType> recreationalVehicles;
    @XmlElement(name = "Relatives")
    protected List<AssociateRelative> relatives;
    @XmlElement(name = "SocialSecurityNumbers")
    protected List<PeopleSsnData> socialSecurityNumbers;
    @XmlElement(name = "Vehicles")
    protected List<VehiclesType> vehicles;
    @XmlElement(name = "Boats")
    protected List<BoatsType> boats;
    @XmlElement(name = "Voters")
    protected List<VotersType> voters;

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link ComprehensiveNameAddressInfo }
     *     
     */
    public ComprehensiveNameAddressInfo getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComprehensiveNameAddressInfo }
     *     
     */
    public void setAddresses(ComprehensiveNameAddressInfo value) {
        this.addresses = value;
    }

    /**
     * Gets the value of the aircrafts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aircrafts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAircrafts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AircraftsType }
     * 
     * 
     */
    public List<AircraftsType> getAircrafts() {
        if (aircrafts == null) {
            aircrafts = new ArrayList<AircraftsType>();
        }
        return this.aircrafts;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aliases property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAliases().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AliasesType }
     * 
     * 
     */
    public List<AliasesType> getAliases() {
        if (aliases == null) {
            aliases = new ArrayList<AliasesType>();
        }
        return this.aliases;
    }

    /**
     * Gets the value of the associates property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the associates property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssociates().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssociateRelative }
     * 
     * 
     */
    public List<AssociateRelative> getAssociates() {
        if (associates == null) {
            associates = new ArrayList<AssociateRelative>();
        }
        return this.associates;
    }

    /**
     * Gets the value of the concealedWeapons property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the concealedWeapons property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getConcealedWeapons().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConcealedWeaponsType }
     * 
     * 
     */
    public List<ConcealedWeaponsType> getConcealedWeapons() {
        if (concealedWeapons == null) {
            concealedWeapons = new ArrayList<ConcealedWeaponsType>();
        }
        return this.concealedWeapons;
    }

    /**
     * Gets the value of the corporateAssociationsAndEmployment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the corporateAssociationsAndEmployment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCorporateAssociationsAndEmployment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EmployersType }
     * 
     * 
     */
    public List<EmployersType> getCorporateAssociationsAndEmployment() {
        if (corporateAssociationsAndEmployment == null) {
            corporateAssociationsAndEmployment = new ArrayList<EmployersType>();
        }
        return this.corporateAssociationsAndEmployment;
    }

    /**
     * Gets the value of the deaRegistrations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deaRegistrations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeaRegistrations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEARegistrationsType }
     * 
     * 
     */
    public List<DEARegistrationsType> getDeaRegistrations() {
        if (deaRegistrations == null) {
            deaRegistrations = new ArrayList<DEARegistrationsType>();
        }
        return this.deaRegistrations;
    }

    /**
     * Gets the value of the driversLicenses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the driversLicenses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDriversLicenses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DriversLicensesType }
     * 
     * 
     */
    public List<DriversLicensesType> getDriversLicenses() {
        if (driversLicenses == null) {
            driversLicenses = new ArrayList<DriversLicensesType>();
        }
        return this.driversLicenses;
    }

    /**
     * Gets the value of the higherEducations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the higherEducations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHigherEducations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HigherEducationsType }
     * 
     * 
     */
    public List<HigherEducationsType> getHigherEducations() {
        if (higherEducations == null) {
            higherEducations = new ArrayList<HigherEducationsType>();
        }
        return this.higherEducations;
    }

    /**
     * Gets the value of the huntingFishing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the huntingFishing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHuntingFishing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HuntersType }
     * 
     * 
     */
    public List<HuntersType> getHuntingFishing() {
        if (huntingFishing == null) {
            huntingFishing = new ArrayList<HuntersType>();
        }
        return this.huntingFishing;
    }

    /**
     * Gets the value of the internetDomains property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internetDomains property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternetDomains().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DomainsType }
     * 
     * 
     */
    public List<DomainsType> getInternetDomains() {
        if (internetDomains == null) {
            internetDomains = new ArrayList<DomainsType>();
        }
        return this.internetDomains;
    }

    /**
     * Gets the value of the neighbors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the neighbors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNeighbors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeighborOutput }
     * 
     * 
     */
    public List<NeighborOutput> getNeighbors() {
        if (neighbors == null) {
            neighbors = new ArrayList<NeighborOutput>();
        }
        return this.neighbors;
    }

    /**
     * Gets the value of the phones property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phones property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhones().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeoplePhoneData }
     * 
     * 
     */
    public List<PeoplePhoneData> getPhones() {
        if (phones == null) {
            phones = new ArrayList<PeoplePhoneData>();
        }
        return this.phones;
    }

    /**
     * Gets the value of the pilots property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pilots property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPilots().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PilotsType }
     * 
     * 
     */
    public List<PilotsType> getPilots() {
        if (pilots == null) {
            pilots = new ArrayList<PilotsType>();
        }
        return this.pilots;
    }

    /**
     * Gets the value of the premiumVehicles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the premiumVehicles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPremiumVehicles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PremiumVehiclesOutput }
     * 
     * 
     */
    public List<PremiumVehiclesOutput> getPremiumVehicles() {
        if (premiumVehicles == null) {
            premiumVehicles = new ArrayList<PremiumVehiclesOutput>();
        }
        return this.premiumVehicles;
    }

    /**
     * Gets the value of the professionalLicenses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the professionalLicenses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfessionalLicenses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfessionalLicensesType }
     * 
     * 
     */
    public List<ProfessionalLicensesType> getProfessionalLicenses() {
        if (professionalLicenses == null) {
            professionalLicenses = new ArrayList<ProfessionalLicensesType>();
        }
        return this.professionalLicenses;
    }

    /**
     * Gets the value of the recreationalVehicles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the recreationalVehicles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRecreationalVehicles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecreationalVehiclesType }
     * 
     * 
     */
    public List<RecreationalVehiclesType> getRecreationalVehicles() {
        if (recreationalVehicles == null) {
            recreationalVehicles = new ArrayList<RecreationalVehiclesType>();
        }
        return this.recreationalVehicles;
    }

    /**
     * Gets the value of the relatives property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatives property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatives().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssociateRelative }
     * 
     * 
     */
    public List<AssociateRelative> getRelatives() {
        if (relatives == null) {
            relatives = new ArrayList<AssociateRelative>();
        }
        return this.relatives;
    }

    /**
     * Gets the value of the socialSecurityNumbers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the socialSecurityNumbers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSocialSecurityNumbers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeopleSsnData }
     * 
     * 
     */
    public List<PeopleSsnData> getSocialSecurityNumbers() {
        if (socialSecurityNumbers == null) {
            socialSecurityNumbers = new ArrayList<PeopleSsnData>();
        }
        return this.socialSecurityNumbers;
    }

    /**
     * Gets the value of the vehicles property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the vehicles property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVehicles().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VehiclesType }
     * 
     * 
     */
    public List<VehiclesType> getVehicles() {
        if (vehicles == null) {
            vehicles = new ArrayList<VehiclesType>();
        }
        return this.vehicles;
    }

    /**
     * Gets the value of the boats property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the boats property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBoats().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BoatsType }
     * 
     * 
     */
    public List<BoatsType> getBoats() {
        if (boats == null) {
            boats = new ArrayList<BoatsType>();
        }
        return this.boats;
    }

    /**
     * Gets the value of the voters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the voters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVoters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VotersType }
     * 
     * 
     */
    public List<VotersType> getVoters() {
        if (voters == null) {
            voters = new ArrayList<VotersType>();
        }
        return this.voters;
    }

}
