//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NeighborOutput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NeighborOutput">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AliasData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborAliasData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NameAddressData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborNameAddressData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PhoneData" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborPhoneData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NeighborOutput", propOrder = {
    "aliasData",
    "nameAddressData",
    "phoneData",
    "individualId"
})
public class NeighborOutput {

    @XmlElement(name = "AliasData")
    protected List<NeighborAliasData> aliasData;
    @XmlElement(name = "NameAddressData")
    protected List<NeighborNameAddressData> nameAddressData;
    @XmlElement(name = "PhoneData")
    protected List<NeighborPhoneData> phoneData;
    @XmlElement(name = "IndividualId")
    protected String individualId;

    /**
     * Gets the value of the aliasData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aliasData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAliasData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeighborAliasData }
     * 
     * 
     */
    public List<NeighborAliasData> getAliasData() {
        if (aliasData == null) {
            aliasData = new ArrayList<NeighborAliasData>();
        }
        return this.aliasData;
    }

    /**
     * Gets the value of the nameAddressData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameAddressData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameAddressData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeighborNameAddressData }
     * 
     * 
     */
    public List<NeighborNameAddressData> getNameAddressData() {
        if (nameAddressData == null) {
            nameAddressData = new ArrayList<NeighborNameAddressData>();
        }
        return this.nameAddressData;
    }

    /**
     * Gets the value of the phoneData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the phoneData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhoneData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NeighborPhoneData }
     * 
     * 
     */
    public List<NeighborPhoneData> getPhoneData() {
        if (phoneData == null) {
            phoneData = new ArrayList<NeighborPhoneData>();
        }
        return this.phoneData;
    }

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

}
