//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.acxiom.schemas.v201110.us.idod.common.RestrictedUseType;


/**
 * <p>Java class for NeighborPhoneData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NeighborPhoneData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndividualLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AddressLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AreaCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CardIssuerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DisconnectDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudMsgCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NXXType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneOrderIndividualAddressLink" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="PhoneRank" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="PhoneStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PhoneStatusRank" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="PhoneTypeDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PublishDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VerifiedDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RestrictedUseInfo" type="{http://schemas.acxiom.com/v201110/us/idod/common}RestrictedUseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NeighborPhoneData", propOrder = {
    "actionDate",
    "individualLink",
    "addressLink",
    "areaCode",
    "cardIssuerId",
    "disconnectDate",
    "fraudMsgCode",
    "nxxType",
    "phoneNumber",
    "phoneOrderIndividualAddressLink",
    "phoneRank",
    "phoneStatus",
    "phoneStatusRank",
    "phoneTypeDescription",
    "publishDate",
    "verifiedDate",
    "restrictedUseInfo"
})
public class NeighborPhoneData {

    @XmlElement(name = "ActionDate")
    protected String actionDate;
    @XmlElement(name = "IndividualLink")
    protected String individualLink;
    @XmlElement(name = "AddressLink")
    protected String addressLink;
    @XmlElement(name = "AreaCode")
    protected String areaCode;
    @XmlElement(name = "CardIssuerId")
    protected String cardIssuerId;
    @XmlElement(name = "DisconnectDate")
    protected String disconnectDate;
    @XmlElement(name = "FraudMsgCode")
    protected String fraudMsgCode;
    @XmlElement(name = "NXXType")
    protected String nxxType;
    @XmlElement(name = "PhoneNumber")
    protected String phoneNumber;
    @XmlElement(name = "PhoneOrderIndividualAddressLink")
    protected long phoneOrderIndividualAddressLink;
    @XmlElement(name = "PhoneRank")
    protected Long phoneRank;
    @XmlElement(name = "PhoneStatus")
    protected String phoneStatus;
    @XmlElement(name = "PhoneStatusRank")
    protected Long phoneStatusRank;
    @XmlElement(name = "PhoneTypeDescription")
    protected String phoneTypeDescription;
    @XmlElement(name = "PublishDate")
    protected String publishDate;
    @XmlElement(name = "VerifiedDate")
    protected String verifiedDate;
    @XmlElement(name = "RestrictedUseInfo")
    protected RestrictedUseType restrictedUseInfo;

    /**
     * Gets the value of the actionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActionDate() {
        return actionDate;
    }

    /**
     * Sets the value of the actionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActionDate(String value) {
        this.actionDate = value;
    }

    /**
     * Gets the value of the individualLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualLink() {
        return individualLink;
    }

    /**
     * Sets the value of the individualLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualLink(String value) {
        this.individualLink = value;
    }

    /**
     * Gets the value of the addressLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressLink() {
        return addressLink;
    }

    /**
     * Sets the value of the addressLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressLink(String value) {
        this.addressLink = value;
    }

    /**
     * Gets the value of the areaCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * Sets the value of the areaCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAreaCode(String value) {
        this.areaCode = value;
    }

    /**
     * Gets the value of the cardIssuerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCardIssuerId() {
        return cardIssuerId;
    }

    /**
     * Sets the value of the cardIssuerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCardIssuerId(String value) {
        this.cardIssuerId = value;
    }

    /**
     * Gets the value of the disconnectDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisconnectDate() {
        return disconnectDate;
    }

    /**
     * Sets the value of the disconnectDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisconnectDate(String value) {
        this.disconnectDate = value;
    }

    /**
     * Gets the value of the fraudMsgCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudMsgCode() {
        return fraudMsgCode;
    }

    /**
     * Sets the value of the fraudMsgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudMsgCode(String value) {
        this.fraudMsgCode = value;
    }

    /**
     * Gets the value of the nxxType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNXXType() {
        return nxxType;
    }

    /**
     * Sets the value of the nxxType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNXXType(String value) {
        this.nxxType = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the phoneOrderIndividualAddressLink property.
     * 
     */
    public long getPhoneOrderIndividualAddressLink() {
        return phoneOrderIndividualAddressLink;
    }

    /**
     * Sets the value of the phoneOrderIndividualAddressLink property.
     * 
     */
    public void setPhoneOrderIndividualAddressLink(long value) {
        this.phoneOrderIndividualAddressLink = value;
    }

    /**
     * Gets the value of the phoneRank property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPhoneRank() {
        return phoneRank;
    }

    /**
     * Sets the value of the phoneRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPhoneRank(Long value) {
        this.phoneRank = value;
    }

    /**
     * Gets the value of the phoneStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneStatus() {
        return phoneStatus;
    }

    /**
     * Sets the value of the phoneStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneStatus(String value) {
        this.phoneStatus = value;
    }

    /**
     * Gets the value of the phoneStatusRank property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPhoneStatusRank() {
        return phoneStatusRank;
    }

    /**
     * Sets the value of the phoneStatusRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPhoneStatusRank(Long value) {
        this.phoneStatusRank = value;
    }

    /**
     * Gets the value of the phoneTypeDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneTypeDescription() {
        return phoneTypeDescription;
    }

    /**
     * Sets the value of the phoneTypeDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneTypeDescription(String value) {
        this.phoneTypeDescription = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishDate(String value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the verifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerifiedDate() {
        return verifiedDate;
    }

    /**
     * Sets the value of the verifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerifiedDate(String value) {
        this.verifiedDate = value;
    }

    /**
     * Gets the value of the restrictedUseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedUseType }
     *     
     */
    public RestrictedUseType getRestrictedUseInfo() {
        return restrictedUseInfo;
    }

    /**
     * Sets the value of the restrictedUseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedUseType }
     *     
     */
    public void setRestrictedUseInfo(RestrictedUseType value) {
        this.restrictedUseInfo = value;
    }

}
