//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NeighborNameAddressData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NeighborNameAddressData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *         &lt;element name="Address" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborAddress" minOccurs="0"/>
 *         &lt;element name="AddressStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AgeInYears" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AddressOnly" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DateEndedSource" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DateOfBirth" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborDOB" minOccurs="0"/>
 *         &lt;element name="DateReportedSource" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DateVerifiedSource" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DsfAccuracyInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DsfDeliverabilityInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DsfDropCount" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="DsfDropInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DwellingUnitSizeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudMsgCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FraudVictimIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Gender" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LORSource" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}NeighborName" minOccurs="0"/>
 *         &lt;element name="OccupancyAddres" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OwnRentSource" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="SpecialAddressTypeFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NeighborNameAddressData", propOrder = {
    "individualId",
    "address",
    "addressStatus",
    "ageInYears",
    "addressOnly",
    "dateEndedSource",
    "dateOfBirth",
    "dateReportedSource",
    "dateVerifiedSource",
    "dsfAccuracyInd",
    "dsfDeliverabilityInd",
    "dsfDropCount",
    "dsfDropInd",
    "dwellingUnitSizeFlag",
    "fraudMsgCode",
    "fraudVictimIndicator",
    "gender",
    "lorSource",
    "name",
    "occupancyAddres",
    "ownRentSource",
    "specialAddressTypeFlag"
})
public class NeighborNameAddressData {

    @XmlElement(name = "IndividualId")
    protected String individualId;
    @XmlElement(name = "Address")
    protected NeighborAddress address;
    @XmlElement(name = "AddressStatus")
    protected String addressStatus;
    @XmlElement(name = "AgeInYears")
    protected Integer ageInYears;
    @XmlElement(name = "AddressOnly")
    protected String addressOnly;
    @XmlElement(name = "DateEndedSource")
    protected Long dateEndedSource;
    @XmlElement(name = "DateOfBirth")
    protected NeighborDOB dateOfBirth;
    @XmlElement(name = "DateReportedSource")
    protected Long dateReportedSource;
    @XmlElement(name = "DateVerifiedSource")
    protected Long dateVerifiedSource;
    @XmlElement(name = "DsfAccuracyInd")
    protected String dsfAccuracyInd;
    @XmlElement(name = "DsfDeliverabilityInd")
    protected String dsfDeliverabilityInd;
    @XmlElement(name = "DsfDropCount")
    protected Long dsfDropCount;
    @XmlElement(name = "DsfDropInd")
    protected String dsfDropInd;
    @XmlElement(name = "DwellingUnitSizeFlag")
    protected String dwellingUnitSizeFlag;
    @XmlElement(name = "FraudMsgCode")
    protected String fraudMsgCode;
    @XmlElement(name = "FraudVictimIndicator")
    protected String fraudVictimIndicator;
    @XmlElement(name = "Gender")
    protected String gender;
    @XmlElement(name = "LORSource")
    protected Long lorSource;
    @XmlElement(name = "Name")
    protected NeighborName name;
    @XmlElement(name = "OccupancyAddres")
    protected String occupancyAddres;
    @XmlElement(name = "OwnRentSource")
    protected Long ownRentSource;
    @XmlElement(name = "SpecialAddressTypeFlag")
    protected String specialAddressTypeFlag;

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link NeighborAddress }
     *     
     */
    public NeighborAddress getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link NeighborAddress }
     *     
     */
    public void setAddress(NeighborAddress value) {
        this.address = value;
    }

    /**
     * Gets the value of the addressStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressStatus() {
        return addressStatus;
    }

    /**
     * Sets the value of the addressStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressStatus(String value) {
        this.addressStatus = value;
    }

    /**
     * Gets the value of the ageInYears property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAgeInYears() {
        return ageInYears;
    }

    /**
     * Sets the value of the ageInYears property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAgeInYears(Integer value) {
        this.ageInYears = value;
    }

    /**
     * Gets the value of the addressOnly property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddressOnly() {
        return addressOnly;
    }

    /**
     * Sets the value of the addressOnly property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddressOnly(String value) {
        this.addressOnly = value;
    }

    /**
     * Gets the value of the dateEndedSource property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDateEndedSource() {
        return dateEndedSource;
    }

    /**
     * Sets the value of the dateEndedSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDateEndedSource(Long value) {
        this.dateEndedSource = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link NeighborDOB }
     *     
     */
    public NeighborDOB getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link NeighborDOB }
     *     
     */
    public void setDateOfBirth(NeighborDOB value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the dateReportedSource property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDateReportedSource() {
        return dateReportedSource;
    }

    /**
     * Sets the value of the dateReportedSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDateReportedSource(Long value) {
        this.dateReportedSource = value;
    }

    /**
     * Gets the value of the dateVerifiedSource property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDateVerifiedSource() {
        return dateVerifiedSource;
    }

    /**
     * Sets the value of the dateVerifiedSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDateVerifiedSource(Long value) {
        this.dateVerifiedSource = value;
    }

    /**
     * Gets the value of the dsfAccuracyInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsfAccuracyInd() {
        return dsfAccuracyInd;
    }

    /**
     * Sets the value of the dsfAccuracyInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsfAccuracyInd(String value) {
        this.dsfAccuracyInd = value;
    }

    /**
     * Gets the value of the dsfDeliverabilityInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsfDeliverabilityInd() {
        return dsfDeliverabilityInd;
    }

    /**
     * Sets the value of the dsfDeliverabilityInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsfDeliverabilityInd(String value) {
        this.dsfDeliverabilityInd = value;
    }

    /**
     * Gets the value of the dsfDropCount property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDsfDropCount() {
        return dsfDropCount;
    }

    /**
     * Sets the value of the dsfDropCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDsfDropCount(Long value) {
        this.dsfDropCount = value;
    }

    /**
     * Gets the value of the dsfDropInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsfDropInd() {
        return dsfDropInd;
    }

    /**
     * Sets the value of the dsfDropInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsfDropInd(String value) {
        this.dsfDropInd = value;
    }

    /**
     * Gets the value of the dwellingUnitSizeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDwellingUnitSizeFlag() {
        return dwellingUnitSizeFlag;
    }

    /**
     * Sets the value of the dwellingUnitSizeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDwellingUnitSizeFlag(String value) {
        this.dwellingUnitSizeFlag = value;
    }

    /**
     * Gets the value of the fraudMsgCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudMsgCode() {
        return fraudMsgCode;
    }

    /**
     * Sets the value of the fraudMsgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudMsgCode(String value) {
        this.fraudMsgCode = value;
    }

    /**
     * Gets the value of the fraudVictimIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudVictimIndicator() {
        return fraudVictimIndicator;
    }

    /**
     * Sets the value of the fraudVictimIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudVictimIndicator(String value) {
        this.fraudVictimIndicator = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the lorSource property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getLORSource() {
        return lorSource;
    }

    /**
     * Sets the value of the lorSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setLORSource(Long value) {
        this.lorSource = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link NeighborName }
     *     
     */
    public NeighborName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link NeighborName }
     *     
     */
    public void setName(NeighborName value) {
        this.name = value;
    }

    /**
     * Gets the value of the occupancyAddres property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOccupancyAddres() {
        return occupancyAddres;
    }

    /**
     * Sets the value of the occupancyAddres property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOccupancyAddres(String value) {
        this.occupancyAddres = value;
    }

    /**
     * Gets the value of the ownRentSource property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOwnRentSource() {
        return ownRentSource;
    }

    /**
     * Sets the value of the ownRentSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOwnRentSource(Long value) {
        this.ownRentSource = value;
    }

    /**
     * Gets the value of the specialAddressTypeFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialAddressTypeFlag() {
        return specialAddressTypeFlag;
    }

    /**
     * Sets the value of the specialAddressTypeFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialAddressTypeFlag(String value) {
        this.specialAddressTypeFlag = value;
    }

}
