//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.acxiom.schemas.v201110.us.idod.comprehensivereport.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Response_QNAME = new QName("http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response", "Response");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.acxiom.schemas.v201110.us.idod.comprehensivereport.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link VoterType }
     * 
     */
    public VoterType createVoterType() {
        return new VoterType();
    }

    /**
     * Create an instance of {@link NeighborAddress }
     * 
     */
    public NeighborAddress createNeighborAddress() {
        return new NeighborAddress();
    }

    /**
     * Create an instance of {@link ConcealedWeaponsType }
     * 
     */
    public ConcealedWeaponsType createConcealedWeaponsType() {
        return new ConcealedWeaponsType();
    }

    /**
     * Create an instance of {@link PeopleNameAddressData }
     * 
     */
    public PeopleNameAddressData createPeopleNameAddressData() {
        return new PeopleNameAddressData();
    }

    /**
     * Create an instance of {@link PeopleContactRestrictedUseInfo }
     * 
     */
    public PeopleContactRestrictedUseInfo createPeopleContactRestrictedUseInfo() {
        return new PeopleContactRestrictedUseInfo();
    }

    /**
     * Create an instance of {@link AliasType }
     * 
     */
    public AliasType createAliasType() {
        return new AliasType();
    }

    /**
     * Create an instance of {@link HigherEducationRestrictedUseType }
     * 
     */
    public HigherEducationRestrictedUseType createHigherEducationRestrictedUseType() {
        return new HigherEducationRestrictedUseType();
    }

    /**
     * Create an instance of {@link AssociateRelativeSsnData }
     * 
     */
    public AssociateRelativeSsnData createAssociateRelativeSsnData() {
        return new AssociateRelativeSsnData();
    }

    /**
     * Create an instance of {@link AircraftType }
     * 
     */
    public AircraftType createAircraftType() {
        return new AircraftType();
    }

    /**
     * Create an instance of {@link PropertyRestrictedUseType }
     * 
     */
    public PropertyRestrictedUseType createPropertyRestrictedUseType() {
        return new PropertyRestrictedUseType();
    }

    /**
     * Create an instance of {@link ProfessionalLicensesType }
     * 
     */
    public ProfessionalLicensesType createProfessionalLicensesType() {
        return new ProfessionalLicensesType();
    }

    /**
     * Create an instance of {@link DEARegistrationType }
     * 
     */
    public DEARegistrationType createDEARegistrationType() {
        return new DEARegistrationType();
    }

    /**
     * Create an instance of {@link AssociateRelativeName }
     * 
     */
    public AssociateRelativeName createAssociateRelativeName() {
        return new AssociateRelativeName();
    }

    /**
     * Create an instance of {@link RecreationalVehiclesType }
     * 
     */
    public RecreationalVehiclesType createRecreationalVehiclesType() {
        return new RecreationalVehiclesType();
    }

    /**
     * Create an instance of {@link VotersType }
     * 
     */
    public VotersType createVotersType() {
        return new VotersType();
    }

    /**
     * Create an instance of {@link NeighborAliasData }
     * 
     */
    public NeighborAliasData createNeighborAliasData() {
        return new NeighborAliasData();
    }

    /**
     * Create an instance of {@link PeopleSsnData }
     * 
     */
    public PeopleSsnData createPeopleSsnData() {
        return new PeopleSsnData();
    }

    /**
     * Create an instance of {@link PropertiesType }
     * 
     */
    public PropertiesType createPropertiesType() {
        return new PropertiesType();
    }

    /**
     * Create an instance of {@link HuntersType }
     * 
     */
    public HuntersType createHuntersType() {
        return new HuntersType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link NeighborOutput }
     * 
     */
    public NeighborOutput createNeighborOutput() {
        return new NeighborOutput();
    }

    /**
     * Create an instance of {@link DEARegistrationsType }
     * 
     */
    public DEARegistrationsType createDEARegistrationsType() {
        return new DEARegistrationsType();
    }

    /**
     * Create an instance of {@link PilotsType }
     * 
     */
    public PilotsType createPilotsType() {
        return new PilotsType();
    }

    /**
     * Create an instance of {@link EmployerType }
     * 
     */
    public EmployerType createEmployerType() {
        return new EmployerType();
    }

    /**
     * Create an instance of {@link AliasesType }
     * 
     */
    public AliasesType createAliasesType() {
        return new AliasesType();
    }

    /**
     * Create an instance of {@link BoatType }
     * 
     */
    public BoatType createBoatType() {
        return new BoatType();
    }

    /**
     * Create an instance of {@link PeopleContactData }
     * 
     */
    public PeopleContactData createPeopleContactData() {
        return new PeopleContactData();
    }

    /**
     * Create an instance of {@link PremiumVehiclesResponseList }
     * 
     */
    public PremiumVehiclesResponseList createPremiumVehiclesResponseList() {
        return new PremiumVehiclesResponseList();
    }

    /**
     * Create an instance of {@link NeighborName }
     * 
     */
    public NeighborName createNeighborName() {
        return new NeighborName();
    }

    /**
     * Create an instance of {@link DomainType }
     * 
     */
    public DomainType createDomainType() {
        return new DomainType();
    }

    /**
     * Create an instance of {@link PremiumVehiclesOutput }
     * 
     */
    public PremiumVehiclesOutput createPremiumVehiclesOutput() {
        return new PremiumVehiclesOutput();
    }

    /**
     * Create an instance of {@link VehiclesType }
     * 
     */
    public VehiclesType createVehiclesType() {
        return new VehiclesType();
    }

    /**
     * Create an instance of {@link NeighborNameAddressData }
     * 
     */
    public NeighborNameAddressData createNeighborNameAddressData() {
        return new NeighborNameAddressData();
    }

    /**
     * Create an instance of {@link NeighborDOB }
     * 
     */
    public NeighborDOB createNeighborDOB() {
        return new NeighborDOB();
    }

    /**
     * Create an instance of {@link NeighborPhoneData }
     * 
     */
    public NeighborPhoneData createNeighborPhoneData() {
        return new NeighborPhoneData();
    }

    /**
     * Create an instance of {@link PeoplePhoneData }
     * 
     */
    public PeoplePhoneData createPeoplePhoneData() {
        return new PeoplePhoneData();
    }

    /**
     * Create an instance of {@link PropertyType }
     * 
     */
    public PropertyType createPropertyType() {
        return new PropertyType();
    }

    /**
     * Create an instance of {@link AssociateRelativeAliasData }
     * 
     */
    public AssociateRelativeAliasData createAssociateRelativeAliasData() {
        return new AssociateRelativeAliasData();
    }

    /**
     * Create an instance of {@link EmployersType }
     * 
     */
    public EmployersType createEmployersType() {
        return new EmployersType();
    }

    /**
     * Create an instance of {@link VehiclesRestrictedUseInfo }
     * 
     */
    public VehiclesRestrictedUseInfo createVehiclesRestrictedUseInfo() {
        return new VehiclesRestrictedUseInfo();
    }

    /**
     * Create an instance of {@link HigherEducationType }
     * 
     */
    public HigherEducationType createHigherEducationType() {
        return new HigherEducationType();
    }

    /**
     * Create an instance of {@link ProfessionalLicenseType }
     * 
     */
    public ProfessionalLicenseType createProfessionalLicenseType() {
        return new ProfessionalLicenseType();
    }

    /**
     * Create an instance of {@link PremiumVehiclesAddress }
     * 
     */
    public PremiumVehiclesAddress createPremiumVehiclesAddress() {
        return new PremiumVehiclesAddress();
    }

    /**
     * Create an instance of {@link AircraftsType }
     * 
     */
    public AircraftsType createAircraftsType() {
        return new AircraftsType();
    }

    /**
     * Create an instance of {@link PremiumVehiclesFeature }
     * 
     */
    public PremiumVehiclesFeature createPremiumVehiclesFeature() {
        return new PremiumVehiclesFeature();
    }

    /**
     * Create an instance of {@link ComprehensiveNameAddressPropertyInfo }
     * 
     */
    public ComprehensiveNameAddressPropertyInfo createComprehensiveNameAddressPropertyInfo() {
        return new ComprehensiveNameAddressPropertyInfo();
    }

    /**
     * Create an instance of {@link PeopleName }
     * 
     */
    public PeopleName createPeopleName() {
        return new PeopleName();
    }

    /**
     * Create an instance of {@link PeopleNameAddressRestrictedUseInfo }
     * 
     */
    public PeopleNameAddressRestrictedUseInfo createPeopleNameAddressRestrictedUseInfo() {
        return new PeopleNameAddressRestrictedUseInfo();
    }

    /**
     * Create an instance of {@link ComprehensiveNameAddressInfo }
     * 
     */
    public ComprehensiveNameAddressInfo createComprehensiveNameAddressInfo() {
        return new ComprehensiveNameAddressInfo();
    }

    /**
     * Create an instance of {@link ConcealedWeaponType }
     * 
     */
    public ConcealedWeaponType createConcealedWeaponType() {
        return new ConcealedWeaponType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link RecreationalVehicleType }
     * 
     */
    public RecreationalVehicleType createRecreationalVehicleType() {
        return new RecreationalVehicleType();
    }

    /**
     * Create an instance of {@link AssociateRelativeNameAddressData }
     * 
     */
    public AssociateRelativeNameAddressData createAssociateRelativeNameAddressData() {
        return new AssociateRelativeNameAddressData();
    }

    /**
     * Create an instance of {@link DomainsType }
     * 
     */
    public DomainsType createDomainsType() {
        return new DomainsType();
    }

    /**
     * Create an instance of {@link AssociateRelative }
     * 
     */
    public AssociateRelative createAssociateRelative() {
        return new AssociateRelative();
    }

    /**
     * Create an instance of {@link MatchResultsType }
     * 
     */
    public MatchResultsType createMatchResultsType() {
        return new MatchResultsType();
    }

    /**
     * Create an instance of {@link EmployerRestrictedUseType }
     * 
     */
    public EmployerRestrictedUseType createEmployerRestrictedUseType() {
        return new EmployerRestrictedUseType();
    }

    /**
     * Create an instance of {@link PeopleAssociativeData }
     * 
     */
    public PeopleAssociativeData createPeopleAssociativeData() {
        return new PeopleAssociativeData();
    }

    /**
     * Create an instance of {@link BoatsType }
     * 
     */
    public BoatsType createBoatsType() {
        return new BoatsType();
    }

    /**
     * Create an instance of {@link AssociateRelativeDOB }
     * 
     */
    public AssociateRelativeDOB createAssociateRelativeDOB() {
        return new AssociateRelativeDOB();
    }

    /**
     * Create an instance of {@link AssociateRelativePhoneData }
     * 
     */
    public AssociateRelativePhoneData createAssociateRelativePhoneData() {
        return new AssociateRelativePhoneData();
    }

    /**
     * Create an instance of {@link DriversLicenseType }
     * 
     */
    public DriversLicenseType createDriversLicenseType() {
        return new DriversLicenseType();
    }

    /**
     * Create an instance of {@link PilotType }
     * 
     */
    public PilotType createPilotType() {
        return new PilotType();
    }

    /**
     * Create an instance of {@link HigherEducationsType }
     * 
     */
    public HigherEducationsType createHigherEducationsType() {
        return new HigherEducationsType();
    }

    /**
     * Create an instance of {@link PremiumVehicle }
     * 
     */
    public PremiumVehicle createPremiumVehicle() {
        return new PremiumVehicle();
    }

    /**
     * Create an instance of {@link PremiumVehiclesIndividual }
     * 
     */
    public PremiumVehiclesIndividual createPremiumVehiclesIndividual() {
        return new PremiumVehiclesIndividual();
    }

    /**
     * Create an instance of {@link DriversLicensesType }
     * 
     */
    public DriversLicensesType createDriversLicensesType() {
        return new DriversLicensesType();
    }

    /**
     * Create an instance of {@link PeopleAssociativeRestrictedUseInfo }
     * 
     */
    public PeopleAssociativeRestrictedUseInfo createPeopleAssociativeRestrictedUseInfo() {
        return new PeopleAssociativeRestrictedUseInfo();
    }

    /**
     * Create an instance of {@link PeopleData }
     * 
     */
    public PeopleData createPeopleData() {
        return new PeopleData();
    }

    /**
     * Create an instance of {@link HunterType }
     * 
     */
    public HunterType createHunterType() {
        return new HunterType();
    }

    /**
     * Create an instance of {@link MatchResultType }
     * 
     */
    public MatchResultType createMatchResultType() {
        return new MatchResultType();
    }

    /**
     * Create an instance of {@link PremiumVehiclesResponse }
     * 
     */
    public PremiumVehiclesResponse createPremiumVehiclesResponse() {
        return new PremiumVehiclesResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response", name = "Response")
    public JAXBElement<ResponseType> createResponse(ResponseType value) {
        return new JAXBElement<ResponseType>(_Response_QNAME, ResponseType.class, null, value);
    }

}
