//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.acxiom.schemas.v201110.us.idod.common.RestrictedUseType;


/**
 * <p>Java class for PeopleSsnData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeopleSsnData">
 *   &lt;complexContent>
 *     &lt;extension base="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PeopleData">
 *       &lt;sequence>
 *         &lt;element name="FraudMsgCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxYearOfIssue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberInvalidSsns" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NumberOfIndividualsWithSsn" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NumberUniqueSsns" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="NumberValidSsns" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="RestrictedUseInfo" type="{http://schemas.acxiom.com/v201110/us/idod/common}RestrictedUseType" minOccurs="0"/>
 *         &lt;element name="Ssn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SsnXlScore" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="StateOfIssue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ValidSsnFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeopleSsnData", propOrder = {
    "fraudMsgCode",
    "maxYearOfIssue",
    "numberInvalidSsns",
    "numberOfIndividualsWithSsn",
    "numberUniqueSsns",
    "numberValidSsns",
    "restrictedUseInfo",
    "ssn",
    "ssnXlScore",
    "stateOfIssue",
    "validSsnFlag"
})
public class PeopleSsnData
    extends PeopleData
{

    @XmlElement(name = "FraudMsgCode")
    protected String fraudMsgCode;
    @XmlElement(name = "MaxYearOfIssue")
    protected String maxYearOfIssue;
    @XmlElement(name = "NumberInvalidSsns")
    protected Integer numberInvalidSsns;
    @XmlElement(name = "NumberOfIndividualsWithSsn")
    protected Integer numberOfIndividualsWithSsn;
    @XmlElement(name = "NumberUniqueSsns")
    protected Integer numberUniqueSsns;
    @XmlElement(name = "NumberValidSsns")
    protected Integer numberValidSsns;
    @XmlElement(name = "RestrictedUseInfo")
    protected RestrictedUseType restrictedUseInfo;
    @XmlElement(name = "Ssn")
    protected String ssn;
    @XmlElement(name = "SsnXlScore")
    protected Long ssnXlScore;
    @XmlElement(name = "StateOfIssue")
    protected String stateOfIssue;
    @XmlElement(name = "ValidSsnFlag")
    protected String validSsnFlag;

    /**
     * Gets the value of the fraudMsgCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFraudMsgCode() {
        return fraudMsgCode;
    }

    /**
     * Sets the value of the fraudMsgCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFraudMsgCode(String value) {
        this.fraudMsgCode = value;
    }

    /**
     * Gets the value of the maxYearOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxYearOfIssue() {
        return maxYearOfIssue;
    }

    /**
     * Sets the value of the maxYearOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxYearOfIssue(String value) {
        this.maxYearOfIssue = value;
    }

    /**
     * Gets the value of the numberInvalidSsns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberInvalidSsns() {
        return numberInvalidSsns;
    }

    /**
     * Sets the value of the numberInvalidSsns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberInvalidSsns(Integer value) {
        this.numberInvalidSsns = value;
    }

    /**
     * Gets the value of the numberOfIndividualsWithSsn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfIndividualsWithSsn() {
        return numberOfIndividualsWithSsn;
    }

    /**
     * Sets the value of the numberOfIndividualsWithSsn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfIndividualsWithSsn(Integer value) {
        this.numberOfIndividualsWithSsn = value;
    }

    /**
     * Gets the value of the numberUniqueSsns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberUniqueSsns() {
        return numberUniqueSsns;
    }

    /**
     * Sets the value of the numberUniqueSsns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberUniqueSsns(Integer value) {
        this.numberUniqueSsns = value;
    }

    /**
     * Gets the value of the numberValidSsns property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberValidSsns() {
        return numberValidSsns;
    }

    /**
     * Sets the value of the numberValidSsns property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberValidSsns(Integer value) {
        this.numberValidSsns = value;
    }

    /**
     * Gets the value of the restrictedUseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RestrictedUseType }
     *     
     */
    public RestrictedUseType getRestrictedUseInfo() {
        return restrictedUseInfo;
    }

    /**
     * Sets the value of the restrictedUseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RestrictedUseType }
     *     
     */
    public void setRestrictedUseInfo(RestrictedUseType value) {
        this.restrictedUseInfo = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the ssnXlScore property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSsnXlScore() {
        return ssnXlScore;
    }

    /**
     * Sets the value of the ssnXlScore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSsnXlScore(Long value) {
        this.ssnXlScore = value;
    }

    /**
     * Gets the value of the stateOfIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateOfIssue() {
        return stateOfIssue;
    }

    /**
     * Sets the value of the stateOfIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateOfIssue(String value) {
        this.stateOfIssue = value;
    }

    /**
     * Gets the value of the validSsnFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidSsnFlag() {
        return validSsnFlag;
    }

    /**
     * Sets the value of the validSsnFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidSsnFlag(String value) {
        this.validSsnFlag = value;
    }

}
