//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PremiumVehiclesResponseList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PremiumVehiclesResponseList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PremiumVehiclesResponse" type="{http://schemas.acxiom.com/v201110/us/idod/comprehensivereport/response}PremiumVehiclesResponse" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PremiumVehiclesResponseList", propOrder = {
    "premiumVehiclesResponse"
})
public class PremiumVehiclesResponseList {

    @XmlElement(name = "PremiumVehiclesResponse")
    protected List<PremiumVehiclesResponse> premiumVehiclesResponse;

    /**
     * Gets the value of the premiumVehiclesResponse property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the premiumVehiclesResponse property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPremiumVehiclesResponse().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PremiumVehiclesResponse }
     * 
     * 
     */
    public List<PremiumVehiclesResponse> getPremiumVehiclesResponse() {
        if (premiumVehiclesResponse == null) {
            premiumVehiclesResponse = new ArrayList<PremiumVehiclesResponse>();
        }
        return this.premiumVehiclesResponse;
    }

}
