//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for premiumVehiclesFeature complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="premiumVehiclesFeature">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AirConditioning" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AntiLockBrakes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BaseShippingWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BodyStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Carburetion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CubicInchDisplacement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Cylinders" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DaytimeRunningLights" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EnginCycles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FourWheelDrive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FrontWheelDrive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FuelCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FullSeriesName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GrossVehicleWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuranceIdentificationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ListPriceVariance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ModelID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalRadio1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalRadio2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalRoof1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalRoof2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalTransmission1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OptionalTransmission2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OriginalBaseListPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OriginalTireSize" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PassiveRestraints" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PowerBrakes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PowerSteering" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PowerWindows" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Radio" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Roof" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecuritySystem" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeriesModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SeriesNameFullSpelling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShippingWeightVariance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateExceptionInsuranceSymbols" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TiltWheel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TonRating" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeNameFullSpelling" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Transmission" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnadjustedInsuranceSymbol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VISReturnCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleSerieratingInsuranceSymbol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VinErrors" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WheelBase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WheelsDriving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "premiumVehiclesFeature", propOrder = {
    "airConditioning",
    "antiLockBrakes",
    "baseShippingWeight",
    "bodyStyle",
    "carburetion",
    "cubicInchDisplacement",
    "cylinders",
    "daytimeRunningLights",
    "enginCycles",
    "fourWheelDrive",
    "frontWheelDrive",
    "fuelCode",
    "fullSeriesName",
    "grossVehicleWeight",
    "insuranceIdentificationNumber",
    "listPriceVariance",
    "modelID",
    "optionalRadio1",
    "optionalRadio2",
    "optionalRoof1",
    "optionalRoof2",
    "optionalTransmission1",
    "optionalTransmission2",
    "originalBaseListPrice",
    "originalTireSize",
    "passiveRestraints",
    "powerBrakes",
    "powerSteering",
    "powerWindows",
    "radio",
    "roof",
    "securitySystem",
    "seriesModel",
    "seriesNameFullSpelling",
    "shippingWeightVariance",
    "stateExceptionInsuranceSymbols",
    "tiltWheel",
    "tonRating",
    "tradeNameFullSpelling",
    "transmission",
    "unadjustedInsuranceSymbol",
    "visReturnCode",
    "vehicleSerieratingInsuranceSymbol",
    "vinErrors",
    "wheelBase",
    "wheelsDriving"
})
public class PremiumVehiclesFeature {

    @XmlElement(name = "AirConditioning")
    protected String airConditioning;
    @XmlElement(name = "AntiLockBrakes")
    protected String antiLockBrakes;
    @XmlElement(name = "BaseShippingWeight")
    protected String baseShippingWeight;
    @XmlElement(name = "BodyStyle")
    protected String bodyStyle;
    @XmlElement(name = "Carburetion")
    protected String carburetion;
    @XmlElement(name = "CubicInchDisplacement")
    protected String cubicInchDisplacement;
    @XmlElement(name = "Cylinders")
    protected String cylinders;
    @XmlElement(name = "DaytimeRunningLights")
    protected String daytimeRunningLights;
    @XmlElement(name = "EnginCycles")
    protected String enginCycles;
    @XmlElement(name = "FourWheelDrive")
    protected String fourWheelDrive;
    @XmlElement(name = "FrontWheelDrive")
    protected String frontWheelDrive;
    @XmlElement(name = "FuelCode")
    protected String fuelCode;
    @XmlElement(name = "FullSeriesName")
    protected String fullSeriesName;
    @XmlElement(name = "GrossVehicleWeight")
    protected String grossVehicleWeight;
    @XmlElement(name = "InsuranceIdentificationNumber")
    protected String insuranceIdentificationNumber;
    @XmlElement(name = "ListPriceVariance")
    protected String listPriceVariance;
    @XmlElement(name = "ModelID")
    protected String modelID;
    @XmlElement(name = "OptionalRadio1")
    protected String optionalRadio1;
    @XmlElement(name = "OptionalRadio2")
    protected String optionalRadio2;
    @XmlElement(name = "OptionalRoof1")
    protected String optionalRoof1;
    @XmlElement(name = "OptionalRoof2")
    protected String optionalRoof2;
    @XmlElement(name = "OptionalTransmission1")
    protected String optionalTransmission1;
    @XmlElement(name = "OptionalTransmission2")
    protected String optionalTransmission2;
    @XmlElement(name = "OriginalBaseListPrice")
    protected String originalBaseListPrice;
    @XmlElement(name = "OriginalTireSize")
    protected String originalTireSize;
    @XmlElement(name = "PassiveRestraints")
    protected String passiveRestraints;
    @XmlElement(name = "PowerBrakes")
    protected String powerBrakes;
    @XmlElement(name = "PowerSteering")
    protected String powerSteering;
    @XmlElement(name = "PowerWindows")
    protected String powerWindows;
    @XmlElement(name = "Radio")
    protected String radio;
    @XmlElement(name = "Roof")
    protected String roof;
    @XmlElement(name = "SecuritySystem")
    protected String securitySystem;
    @XmlElement(name = "SeriesModel")
    protected String seriesModel;
    @XmlElement(name = "SeriesNameFullSpelling")
    protected String seriesNameFullSpelling;
    @XmlElement(name = "ShippingWeightVariance")
    protected String shippingWeightVariance;
    @XmlElement(name = "StateExceptionInsuranceSymbols")
    protected String stateExceptionInsuranceSymbols;
    @XmlElement(name = "TiltWheel")
    protected String tiltWheel;
    @XmlElement(name = "TonRating")
    protected String tonRating;
    @XmlElement(name = "TradeNameFullSpelling")
    protected String tradeNameFullSpelling;
    @XmlElement(name = "Transmission")
    protected String transmission;
    @XmlElement(name = "UnadjustedInsuranceSymbol")
    protected String unadjustedInsuranceSymbol;
    @XmlElement(name = "VISReturnCode")
    protected String visReturnCode;
    @XmlElement(name = "VehicleSerieratingInsuranceSymbol")
    protected String vehicleSerieratingInsuranceSymbol;
    @XmlElement(name = "VinErrors")
    protected String vinErrors;
    @XmlElement(name = "WheelBase")
    protected String wheelBase;
    @XmlElement(name = "WheelsDriving")
    protected String wheelsDriving;

    /**
     * Gets the value of the airConditioning property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirConditioning() {
        return airConditioning;
    }

    /**
     * Sets the value of the airConditioning property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirConditioning(String value) {
        this.airConditioning = value;
    }

    /**
     * Gets the value of the antiLockBrakes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAntiLockBrakes() {
        return antiLockBrakes;
    }

    /**
     * Sets the value of the antiLockBrakes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAntiLockBrakes(String value) {
        this.antiLockBrakes = value;
    }

    /**
     * Gets the value of the baseShippingWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseShippingWeight() {
        return baseShippingWeight;
    }

    /**
     * Sets the value of the baseShippingWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseShippingWeight(String value) {
        this.baseShippingWeight = value;
    }

    /**
     * Gets the value of the bodyStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBodyStyle() {
        return bodyStyle;
    }

    /**
     * Sets the value of the bodyStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBodyStyle(String value) {
        this.bodyStyle = value;
    }

    /**
     * Gets the value of the carburetion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarburetion() {
        return carburetion;
    }

    /**
     * Sets the value of the carburetion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarburetion(String value) {
        this.carburetion = value;
    }

    /**
     * Gets the value of the cubicInchDisplacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCubicInchDisplacement() {
        return cubicInchDisplacement;
    }

    /**
     * Sets the value of the cubicInchDisplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCubicInchDisplacement(String value) {
        this.cubicInchDisplacement = value;
    }

    /**
     * Gets the value of the cylinders property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCylinders() {
        return cylinders;
    }

    /**
     * Sets the value of the cylinders property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCylinders(String value) {
        this.cylinders = value;
    }

    /**
     * Gets the value of the daytimeRunningLights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDaytimeRunningLights() {
        return daytimeRunningLights;
    }

    /**
     * Sets the value of the daytimeRunningLights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDaytimeRunningLights(String value) {
        this.daytimeRunningLights = value;
    }

    /**
     * Gets the value of the enginCycles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnginCycles() {
        return enginCycles;
    }

    /**
     * Sets the value of the enginCycles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnginCycles(String value) {
        this.enginCycles = value;
    }

    /**
     * Gets the value of the fourWheelDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFourWheelDrive() {
        return fourWheelDrive;
    }

    /**
     * Sets the value of the fourWheelDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFourWheelDrive(String value) {
        this.fourWheelDrive = value;
    }

    /**
     * Gets the value of the frontWheelDrive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrontWheelDrive() {
        return frontWheelDrive;
    }

    /**
     * Sets the value of the frontWheelDrive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrontWheelDrive(String value) {
        this.frontWheelDrive = value;
    }

    /**
     * Gets the value of the fuelCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelCode() {
        return fuelCode;
    }

    /**
     * Sets the value of the fuelCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelCode(String value) {
        this.fuelCode = value;
    }

    /**
     * Gets the value of the fullSeriesName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullSeriesName() {
        return fullSeriesName;
    }

    /**
     * Sets the value of the fullSeriesName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullSeriesName(String value) {
        this.fullSeriesName = value;
    }

    /**
     * Gets the value of the grossVehicleWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossVehicleWeight() {
        return grossVehicleWeight;
    }

    /**
     * Sets the value of the grossVehicleWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossVehicleWeight(String value) {
        this.grossVehicleWeight = value;
    }

    /**
     * Gets the value of the insuranceIdentificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuranceIdentificationNumber() {
        return insuranceIdentificationNumber;
    }

    /**
     * Sets the value of the insuranceIdentificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuranceIdentificationNumber(String value) {
        this.insuranceIdentificationNumber = value;
    }

    /**
     * Gets the value of the listPriceVariance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListPriceVariance() {
        return listPriceVariance;
    }

    /**
     * Sets the value of the listPriceVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListPriceVariance(String value) {
        this.listPriceVariance = value;
    }

    /**
     * Gets the value of the modelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModelID() {
        return modelID;
    }

    /**
     * Sets the value of the modelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModelID(String value) {
        this.modelID = value;
    }

    /**
     * Gets the value of the optionalRadio1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalRadio1() {
        return optionalRadio1;
    }

    /**
     * Sets the value of the optionalRadio1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalRadio1(String value) {
        this.optionalRadio1 = value;
    }

    /**
     * Gets the value of the optionalRadio2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalRadio2() {
        return optionalRadio2;
    }

    /**
     * Sets the value of the optionalRadio2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalRadio2(String value) {
        this.optionalRadio2 = value;
    }

    /**
     * Gets the value of the optionalRoof1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalRoof1() {
        return optionalRoof1;
    }

    /**
     * Sets the value of the optionalRoof1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalRoof1(String value) {
        this.optionalRoof1 = value;
    }

    /**
     * Gets the value of the optionalRoof2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalRoof2() {
        return optionalRoof2;
    }

    /**
     * Sets the value of the optionalRoof2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalRoof2(String value) {
        this.optionalRoof2 = value;
    }

    /**
     * Gets the value of the optionalTransmission1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalTransmission1() {
        return optionalTransmission1;
    }

    /**
     * Sets the value of the optionalTransmission1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalTransmission1(String value) {
        this.optionalTransmission1 = value;
    }

    /**
     * Gets the value of the optionalTransmission2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionalTransmission2() {
        return optionalTransmission2;
    }

    /**
     * Sets the value of the optionalTransmission2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionalTransmission2(String value) {
        this.optionalTransmission2 = value;
    }

    /**
     * Gets the value of the originalBaseListPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalBaseListPrice() {
        return originalBaseListPrice;
    }

    /**
     * Sets the value of the originalBaseListPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalBaseListPrice(String value) {
        this.originalBaseListPrice = value;
    }

    /**
     * Gets the value of the originalTireSize property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalTireSize() {
        return originalTireSize;
    }

    /**
     * Sets the value of the originalTireSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalTireSize(String value) {
        this.originalTireSize = value;
    }

    /**
     * Gets the value of the passiveRestraints property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassiveRestraints() {
        return passiveRestraints;
    }

    /**
     * Sets the value of the passiveRestraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassiveRestraints(String value) {
        this.passiveRestraints = value;
    }

    /**
     * Gets the value of the powerBrakes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerBrakes() {
        return powerBrakes;
    }

    /**
     * Sets the value of the powerBrakes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerBrakes(String value) {
        this.powerBrakes = value;
    }

    /**
     * Gets the value of the powerSteering property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerSteering() {
        return powerSteering;
    }

    /**
     * Sets the value of the powerSteering property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerSteering(String value) {
        this.powerSteering = value;
    }

    /**
     * Gets the value of the powerWindows property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPowerWindows() {
        return powerWindows;
    }

    /**
     * Sets the value of the powerWindows property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPowerWindows(String value) {
        this.powerWindows = value;
    }

    /**
     * Gets the value of the radio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadio() {
        return radio;
    }

    /**
     * Sets the value of the radio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadio(String value) {
        this.radio = value;
    }

    /**
     * Gets the value of the roof property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoof() {
        return roof;
    }

    /**
     * Sets the value of the roof property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoof(String value) {
        this.roof = value;
    }

    /**
     * Gets the value of the securitySystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecuritySystem() {
        return securitySystem;
    }

    /**
     * Sets the value of the securitySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecuritySystem(String value) {
        this.securitySystem = value;
    }

    /**
     * Gets the value of the seriesModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesModel() {
        return seriesModel;
    }

    /**
     * Sets the value of the seriesModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesModel(String value) {
        this.seriesModel = value;
    }

    /**
     * Gets the value of the seriesNameFullSpelling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeriesNameFullSpelling() {
        return seriesNameFullSpelling;
    }

    /**
     * Sets the value of the seriesNameFullSpelling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeriesNameFullSpelling(String value) {
        this.seriesNameFullSpelling = value;
    }

    /**
     * Gets the value of the shippingWeightVariance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShippingWeightVariance() {
        return shippingWeightVariance;
    }

    /**
     * Sets the value of the shippingWeightVariance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShippingWeightVariance(String value) {
        this.shippingWeightVariance = value;
    }

    /**
     * Gets the value of the stateExceptionInsuranceSymbols property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateExceptionInsuranceSymbols() {
        return stateExceptionInsuranceSymbols;
    }

    /**
     * Sets the value of the stateExceptionInsuranceSymbols property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateExceptionInsuranceSymbols(String value) {
        this.stateExceptionInsuranceSymbols = value;
    }

    /**
     * Gets the value of the tiltWheel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTiltWheel() {
        return tiltWheel;
    }

    /**
     * Sets the value of the tiltWheel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTiltWheel(String value) {
        this.tiltWheel = value;
    }

    /**
     * Gets the value of the tonRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTonRating() {
        return tonRating;
    }

    /**
     * Sets the value of the tonRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTonRating(String value) {
        this.tonRating = value;
    }

    /**
     * Gets the value of the tradeNameFullSpelling property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeNameFullSpelling() {
        return tradeNameFullSpelling;
    }

    /**
     * Sets the value of the tradeNameFullSpelling property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeNameFullSpelling(String value) {
        this.tradeNameFullSpelling = value;
    }

    /**
     * Gets the value of the transmission property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransmission() {
        return transmission;
    }

    /**
     * Sets the value of the transmission property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransmission(String value) {
        this.transmission = value;
    }

    /**
     * Gets the value of the unadjustedInsuranceSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnadjustedInsuranceSymbol() {
        return unadjustedInsuranceSymbol;
    }

    /**
     * Sets the value of the unadjustedInsuranceSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnadjustedInsuranceSymbol(String value) {
        this.unadjustedInsuranceSymbol = value;
    }

    /**
     * Gets the value of the visReturnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVISReturnCode() {
        return visReturnCode;
    }

    /**
     * Sets the value of the visReturnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVISReturnCode(String value) {
        this.visReturnCode = value;
    }

    /**
     * Gets the value of the vehicleSerieratingInsuranceSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleSerieratingInsuranceSymbol() {
        return vehicleSerieratingInsuranceSymbol;
    }

    /**
     * Sets the value of the vehicleSerieratingInsuranceSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleSerieratingInsuranceSymbol(String value) {
        this.vehicleSerieratingInsuranceSymbol = value;
    }

    /**
     * Gets the value of the vinErrors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVinErrors() {
        return vinErrors;
    }

    /**
     * Sets the value of the vinErrors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVinErrors(String value) {
        this.vinErrors = value;
    }

    /**
     * Gets the value of the wheelBase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWheelBase() {
        return wheelBase;
    }

    /**
     * Sets the value of the wheelBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWheelBase(String value) {
        this.wheelBase = value;
    }

    /**
     * Gets the value of the wheelsDriving property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWheelsDriving() {
        return wheelsDriving;
    }

    /**
     * Sets the value of the wheelsDriving property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWheelsDriving(String value) {
        this.wheelsDriving = value;
    }

}
