//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecreationalVehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecreationalVehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AcquisitionDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affiliation1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Affiliation2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AuditId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BreadthFeet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CancelDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Capacity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CertificateId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CertifyDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChangeDate1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ChangeDate2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DecalId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DollarOne" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DollarTwo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EngineDisplacement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EngineId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExpireDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FuelType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HailingCountry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HailingPort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HomePort" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HorsePower" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HullBuildersName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HullConstruction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HullHinNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HullId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ImoNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndexNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IssueProcessDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItcGrossTons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ItcNetTons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LastActivityDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LengthFeet" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MakeModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManufId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ManufactureYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NameOfVessel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberWheels" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Odometer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Original" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OwnerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonsHeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PersonsWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlateCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PollutionControl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrimaryUse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Propulsion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PurchaseDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PurgeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RegistrationStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReinstateDate1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReinstateDate2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RenewDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReportingAgency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SecondaryColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SelfPropelled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipyardBuiltIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SpecialRegistration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StateCountryPrimaryUse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StatePurchasedIn" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StorageLocation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TagNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TaxOne" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TitleId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TitleStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TypeOfVehicle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UscgId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UscgRegistry" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UscgTradeInd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehDepth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VesselType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WeightLbs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WeightTons" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecreationalVehicleType", propOrder = {
    "acquisitionDate",
    "affiliation1",
    "affiliation2",
    "auditId",
    "breadthFeet",
    "cancelDate",
    "capacity",
    "certificateId",
    "certifyDate",
    "changeDate1",
    "changeDate2",
    "decalId",
    "dollarOne",
    "dollarTwo",
    "engineDisplacement",
    "engineId",
    "expireDate",
    "fuelType",
    "hailingCountry",
    "hailingPort",
    "homePort",
    "horsePower",
    "hullBuildersName",
    "hullConstruction",
    "hullHinNumber",
    "hullId",
    "imoNumber",
    "indexNumber",
    "issueProcessDate",
    "itcGrossTons",
    "itcNetTons",
    "lastActivityDate",
    "lengthFeet",
    "makeModel",
    "manufId",
    "manufactureYear",
    "nameOfVessel",
    "numberWheels",
    "odometer",
    "original",
    "ownerType",
    "personsHeight",
    "personsWeight",
    "plateCode",
    "pollutionControl",
    "primaryColor",
    "primaryUse",
    "propulsion",
    "purchaseDate",
    "purgeDate",
    "regState",
    "registrationDate",
    "registrationStatus",
    "reinstateDate1",
    "reinstateDate2",
    "renewDate",
    "reportingAgency",
    "secondaryColor",
    "selfPropelled",
    "shipyardBuiltIn",
    "specialRegistration",
    "stateCountryPrimaryUse",
    "statePurchasedIn",
    "storageLocation",
    "tagNumber",
    "taxOne",
    "titleId",
    "titleStatus",
    "typeOfVehicle",
    "uscgId",
    "uscgRegistry",
    "uscgTradeInd",
    "vehDepth",
    "vesselType",
    "weightLbs",
    "weightTons"
})
public class RecreationalVehicleType {

    @XmlElement(name = "AcquisitionDate")
    protected String acquisitionDate;
    @XmlElement(name = "Affiliation1")
    protected String affiliation1;
    @XmlElement(name = "Affiliation2")
    protected String affiliation2;
    @XmlElement(name = "AuditId")
    protected String auditId;
    @XmlElement(name = "BreadthFeet")
    protected String breadthFeet;
    @XmlElement(name = "CancelDate")
    protected String cancelDate;
    @XmlElement(name = "Capacity")
    protected String capacity;
    @XmlElement(name = "CertificateId")
    protected String certificateId;
    @XmlElement(name = "CertifyDate")
    protected String certifyDate;
    @XmlElement(name = "ChangeDate1")
    protected String changeDate1;
    @XmlElement(name = "ChangeDate2")
    protected String changeDate2;
    @XmlElement(name = "DecalId")
    protected String decalId;
    @XmlElement(name = "DollarOne")
    protected String dollarOne;
    @XmlElement(name = "DollarTwo")
    protected String dollarTwo;
    @XmlElement(name = "EngineDisplacement")
    protected String engineDisplacement;
    @XmlElement(name = "EngineId")
    protected String engineId;
    @XmlElement(name = "ExpireDate")
    protected String expireDate;
    @XmlElement(name = "FuelType")
    protected String fuelType;
    @XmlElement(name = "HailingCountry")
    protected String hailingCountry;
    @XmlElement(name = "HailingPort")
    protected String hailingPort;
    @XmlElement(name = "HomePort")
    protected String homePort;
    @XmlElement(name = "HorsePower")
    protected String horsePower;
    @XmlElement(name = "HullBuildersName")
    protected String hullBuildersName;
    @XmlElement(name = "HullConstruction")
    protected String hullConstruction;
    @XmlElement(name = "HullHinNumber")
    protected String hullHinNumber;
    @XmlElement(name = "HullId")
    protected String hullId;
    @XmlElement(name = "ImoNumber")
    protected String imoNumber;
    @XmlElement(name = "IndexNumber")
    protected String indexNumber;
    @XmlElement(name = "IssueProcessDate")
    protected String issueProcessDate;
    @XmlElement(name = "ItcGrossTons")
    protected String itcGrossTons;
    @XmlElement(name = "ItcNetTons")
    protected String itcNetTons;
    @XmlElement(name = "LastActivityDate")
    protected String lastActivityDate;
    @XmlElement(name = "LengthFeet")
    protected String lengthFeet;
    @XmlElement(name = "MakeModel")
    protected String makeModel;
    @XmlElement(name = "ManufId")
    protected String manufId;
    @XmlElement(name = "ManufactureYear")
    protected String manufactureYear;
    @XmlElement(name = "NameOfVessel")
    protected String nameOfVessel;
    @XmlElement(name = "NumberWheels")
    protected String numberWheels;
    @XmlElement(name = "Odometer")
    protected String odometer;
    @XmlElement(name = "Original")
    protected String original;
    @XmlElement(name = "OwnerType")
    protected String ownerType;
    @XmlElement(name = "PersonsHeight")
    protected String personsHeight;
    @XmlElement(name = "PersonsWeight")
    protected String personsWeight;
    @XmlElement(name = "PlateCode")
    protected String plateCode;
    @XmlElement(name = "PollutionControl")
    protected String pollutionControl;
    @XmlElement(name = "PrimaryColor")
    protected String primaryColor;
    @XmlElement(name = "PrimaryUse")
    protected String primaryUse;
    @XmlElement(name = "Propulsion")
    protected String propulsion;
    @XmlElement(name = "PurchaseDate")
    protected String purchaseDate;
    @XmlElement(name = "PurgeDate")
    protected String purgeDate;
    @XmlElement(name = "RegState")
    protected String regState;
    @XmlElement(name = "RegistrationDate")
    protected String registrationDate;
    @XmlElement(name = "RegistrationStatus")
    protected String registrationStatus;
    @XmlElement(name = "ReinstateDate1")
    protected String reinstateDate1;
    @XmlElement(name = "ReinstateDate2")
    protected String reinstateDate2;
    @XmlElement(name = "RenewDate")
    protected String renewDate;
    @XmlElement(name = "ReportingAgency")
    protected String reportingAgency;
    @XmlElement(name = "SecondaryColor")
    protected String secondaryColor;
    @XmlElement(name = "SelfPropelled")
    protected String selfPropelled;
    @XmlElement(name = "ShipyardBuiltIn")
    protected String shipyardBuiltIn;
    @XmlElement(name = "SpecialRegistration")
    protected String specialRegistration;
    @XmlElement(name = "StateCountryPrimaryUse")
    protected String stateCountryPrimaryUse;
    @XmlElement(name = "StatePurchasedIn")
    protected String statePurchasedIn;
    @XmlElement(name = "StorageLocation")
    protected String storageLocation;
    @XmlElement(name = "TagNumber")
    protected String tagNumber;
    @XmlElement(name = "TaxOne")
    protected String taxOne;
    @XmlElement(name = "TitleId")
    protected String titleId;
    @XmlElement(name = "TitleStatus")
    protected String titleStatus;
    @XmlElement(name = "TypeOfVehicle")
    protected String typeOfVehicle;
    @XmlElement(name = "UscgId")
    protected String uscgId;
    @XmlElement(name = "UscgRegistry")
    protected String uscgRegistry;
    @XmlElement(name = "UscgTradeInd")
    protected String uscgTradeInd;
    @XmlElement(name = "VehDepth")
    protected String vehDepth;
    @XmlElement(name = "VesselType")
    protected String vesselType;
    @XmlElement(name = "WeightLbs")
    protected String weightLbs;
    @XmlElement(name = "WeightTons")
    protected String weightTons;

    /**
     * Gets the value of the acquisitionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcquisitionDate() {
        return acquisitionDate;
    }

    /**
     * Sets the value of the acquisitionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcquisitionDate(String value) {
        this.acquisitionDate = value;
    }

    /**
     * Gets the value of the affiliation1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliation1() {
        return affiliation1;
    }

    /**
     * Sets the value of the affiliation1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliation1(String value) {
        this.affiliation1 = value;
    }

    /**
     * Gets the value of the affiliation2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAffiliation2() {
        return affiliation2;
    }

    /**
     * Sets the value of the affiliation2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAffiliation2(String value) {
        this.affiliation2 = value;
    }

    /**
     * Gets the value of the auditId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuditId() {
        return auditId;
    }

    /**
     * Sets the value of the auditId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuditId(String value) {
        this.auditId = value;
    }

    /**
     * Gets the value of the breadthFeet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBreadthFeet() {
        return breadthFeet;
    }

    /**
     * Sets the value of the breadthFeet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBreadthFeet(String value) {
        this.breadthFeet = value;
    }

    /**
     * Gets the value of the cancelDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancelDate() {
        return cancelDate;
    }

    /**
     * Sets the value of the cancelDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancelDate(String value) {
        this.cancelDate = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapacity(String value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the certificateId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateId() {
        return certificateId;
    }

    /**
     * Sets the value of the certificateId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateId(String value) {
        this.certificateId = value;
    }

    /**
     * Gets the value of the certifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertifyDate() {
        return certifyDate;
    }

    /**
     * Sets the value of the certifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertifyDate(String value) {
        this.certifyDate = value;
    }

    /**
     * Gets the value of the changeDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeDate1() {
        return changeDate1;
    }

    /**
     * Sets the value of the changeDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeDate1(String value) {
        this.changeDate1 = value;
    }

    /**
     * Gets the value of the changeDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeDate2() {
        return changeDate2;
    }

    /**
     * Sets the value of the changeDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeDate2(String value) {
        this.changeDate2 = value;
    }

    /**
     * Gets the value of the decalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecalId() {
        return decalId;
    }

    /**
     * Sets the value of the decalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecalId(String value) {
        this.decalId = value;
    }

    /**
     * Gets the value of the dollarOne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDollarOne() {
        return dollarOne;
    }

    /**
     * Sets the value of the dollarOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDollarOne(String value) {
        this.dollarOne = value;
    }

    /**
     * Gets the value of the dollarTwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDollarTwo() {
        return dollarTwo;
    }

    /**
     * Sets the value of the dollarTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDollarTwo(String value) {
        this.dollarTwo = value;
    }

    /**
     * Gets the value of the engineDisplacement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineDisplacement() {
        return engineDisplacement;
    }

    /**
     * Sets the value of the engineDisplacement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineDisplacement(String value) {
        this.engineDisplacement = value;
    }

    /**
     * Gets the value of the engineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEngineId() {
        return engineId;
    }

    /**
     * Sets the value of the engineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEngineId(String value) {
        this.engineId = value;
    }

    /**
     * Gets the value of the expireDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpireDate() {
        return expireDate;
    }

    /**
     * Sets the value of the expireDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpireDate(String value) {
        this.expireDate = value;
    }

    /**
     * Gets the value of the fuelType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFuelType() {
        return fuelType;
    }

    /**
     * Sets the value of the fuelType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFuelType(String value) {
        this.fuelType = value;
    }

    /**
     * Gets the value of the hailingCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHailingCountry() {
        return hailingCountry;
    }

    /**
     * Sets the value of the hailingCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHailingCountry(String value) {
        this.hailingCountry = value;
    }

    /**
     * Gets the value of the hailingPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHailingPort() {
        return hailingPort;
    }

    /**
     * Sets the value of the hailingPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHailingPort(String value) {
        this.hailingPort = value;
    }

    /**
     * Gets the value of the homePort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHomePort() {
        return homePort;
    }

    /**
     * Sets the value of the homePort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHomePort(String value) {
        this.homePort = value;
    }

    /**
     * Gets the value of the horsePower property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHorsePower() {
        return horsePower;
    }

    /**
     * Sets the value of the horsePower property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHorsePower(String value) {
        this.horsePower = value;
    }

    /**
     * Gets the value of the hullBuildersName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullBuildersName() {
        return hullBuildersName;
    }

    /**
     * Sets the value of the hullBuildersName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullBuildersName(String value) {
        this.hullBuildersName = value;
    }

    /**
     * Gets the value of the hullConstruction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullConstruction() {
        return hullConstruction;
    }

    /**
     * Sets the value of the hullConstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullConstruction(String value) {
        this.hullConstruction = value;
    }

    /**
     * Gets the value of the hullHinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullHinNumber() {
        return hullHinNumber;
    }

    /**
     * Sets the value of the hullHinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullHinNumber(String value) {
        this.hullHinNumber = value;
    }

    /**
     * Gets the value of the hullId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHullId() {
        return hullId;
    }

    /**
     * Sets the value of the hullId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHullId(String value) {
        this.hullId = value;
    }

    /**
     * Gets the value of the imoNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImoNumber() {
        return imoNumber;
    }

    /**
     * Sets the value of the imoNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImoNumber(String value) {
        this.imoNumber = value;
    }

    /**
     * Gets the value of the indexNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndexNumber() {
        return indexNumber;
    }

    /**
     * Sets the value of the indexNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndexNumber(String value) {
        this.indexNumber = value;
    }

    /**
     * Gets the value of the issueProcessDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueProcessDate() {
        return issueProcessDate;
    }

    /**
     * Sets the value of the issueProcessDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueProcessDate(String value) {
        this.issueProcessDate = value;
    }

    /**
     * Gets the value of the itcGrossTons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItcGrossTons() {
        return itcGrossTons;
    }

    /**
     * Sets the value of the itcGrossTons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItcGrossTons(String value) {
        this.itcGrossTons = value;
    }

    /**
     * Gets the value of the itcNetTons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getItcNetTons() {
        return itcNetTons;
    }

    /**
     * Sets the value of the itcNetTons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setItcNetTons(String value) {
        this.itcNetTons = value;
    }

    /**
     * Gets the value of the lastActivityDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastActivityDate() {
        return lastActivityDate;
    }

    /**
     * Sets the value of the lastActivityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastActivityDate(String value) {
        this.lastActivityDate = value;
    }

    /**
     * Gets the value of the lengthFeet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLengthFeet() {
        return lengthFeet;
    }

    /**
     * Sets the value of the lengthFeet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLengthFeet(String value) {
        this.lengthFeet = value;
    }

    /**
     * Gets the value of the makeModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakeModel() {
        return makeModel;
    }

    /**
     * Sets the value of the makeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakeModel(String value) {
        this.makeModel = value;
    }

    /**
     * Gets the value of the manufId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufId() {
        return manufId;
    }

    /**
     * Sets the value of the manufId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufId(String value) {
        this.manufId = value;
    }

    /**
     * Gets the value of the manufactureYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufactureYear() {
        return manufactureYear;
    }

    /**
     * Sets the value of the manufactureYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufactureYear(String value) {
        this.manufactureYear = value;
    }

    /**
     * Gets the value of the nameOfVessel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameOfVessel() {
        return nameOfVessel;
    }

    /**
     * Sets the value of the nameOfVessel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameOfVessel(String value) {
        this.nameOfVessel = value;
    }

    /**
     * Gets the value of the numberWheels property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberWheels() {
        return numberWheels;
    }

    /**
     * Sets the value of the numberWheels property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberWheels(String value) {
        this.numberWheels = value;
    }

    /**
     * Gets the value of the odometer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOdometer() {
        return odometer;
    }

    /**
     * Sets the value of the odometer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOdometer(String value) {
        this.odometer = value;
    }

    /**
     * Gets the value of the original property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginal() {
        return original;
    }

    /**
     * Sets the value of the original property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginal(String value) {
        this.original = value;
    }

    /**
     * Gets the value of the ownerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnerType() {
        return ownerType;
    }

    /**
     * Sets the value of the ownerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnerType(String value) {
        this.ownerType = value;
    }

    /**
     * Gets the value of the personsHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonsHeight() {
        return personsHeight;
    }

    /**
     * Sets the value of the personsHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonsHeight(String value) {
        this.personsHeight = value;
    }

    /**
     * Gets the value of the personsWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonsWeight() {
        return personsWeight;
    }

    /**
     * Sets the value of the personsWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonsWeight(String value) {
        this.personsWeight = value;
    }

    /**
     * Gets the value of the plateCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlateCode() {
        return plateCode;
    }

    /**
     * Sets the value of the plateCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlateCode(String value) {
        this.plateCode = value;
    }

    /**
     * Gets the value of the pollutionControl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPollutionControl() {
        return pollutionControl;
    }

    /**
     * Sets the value of the pollutionControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPollutionControl(String value) {
        this.pollutionControl = value;
    }

    /**
     * Gets the value of the primaryColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryColor() {
        return primaryColor;
    }

    /**
     * Sets the value of the primaryColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryColor(String value) {
        this.primaryColor = value;
    }

    /**
     * Gets the value of the primaryUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryUse() {
        return primaryUse;
    }

    /**
     * Sets the value of the primaryUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryUse(String value) {
        this.primaryUse = value;
    }

    /**
     * Gets the value of the propulsion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPropulsion() {
        return propulsion;
    }

    /**
     * Sets the value of the propulsion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPropulsion(String value) {
        this.propulsion = value;
    }

    /**
     * Gets the value of the purchaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurchaseDate() {
        return purchaseDate;
    }

    /**
     * Sets the value of the purchaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurchaseDate(String value) {
        this.purchaseDate = value;
    }

    /**
     * Gets the value of the purgeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurgeDate() {
        return purgeDate;
    }

    /**
     * Sets the value of the purgeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurgeDate(String value) {
        this.purgeDate = value;
    }

    /**
     * Gets the value of the regState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegState() {
        return regState;
    }

    /**
     * Sets the value of the regState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegState(String value) {
        this.regState = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationDate(String value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the registrationStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationStatus() {
        return registrationStatus;
    }

    /**
     * Sets the value of the registrationStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationStatus(String value) {
        this.registrationStatus = value;
    }

    /**
     * Gets the value of the reinstateDate1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReinstateDate1() {
        return reinstateDate1;
    }

    /**
     * Sets the value of the reinstateDate1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReinstateDate1(String value) {
        this.reinstateDate1 = value;
    }

    /**
     * Gets the value of the reinstateDate2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReinstateDate2() {
        return reinstateDate2;
    }

    /**
     * Sets the value of the reinstateDate2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReinstateDate2(String value) {
        this.reinstateDate2 = value;
    }

    /**
     * Gets the value of the renewDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewDate() {
        return renewDate;
    }

    /**
     * Sets the value of the renewDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewDate(String value) {
        this.renewDate = value;
    }

    /**
     * Gets the value of the reportingAgency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingAgency() {
        return reportingAgency;
    }

    /**
     * Sets the value of the reportingAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingAgency(String value) {
        this.reportingAgency = value;
    }

    /**
     * Gets the value of the secondaryColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecondaryColor() {
        return secondaryColor;
    }

    /**
     * Sets the value of the secondaryColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecondaryColor(String value) {
        this.secondaryColor = value;
    }

    /**
     * Gets the value of the selfPropelled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfPropelled() {
        return selfPropelled;
    }

    /**
     * Sets the value of the selfPropelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfPropelled(String value) {
        this.selfPropelled = value;
    }

    /**
     * Gets the value of the shipyardBuiltIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipyardBuiltIn() {
        return shipyardBuiltIn;
    }

    /**
     * Sets the value of the shipyardBuiltIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipyardBuiltIn(String value) {
        this.shipyardBuiltIn = value;
    }

    /**
     * Gets the value of the specialRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialRegistration() {
        return specialRegistration;
    }

    /**
     * Sets the value of the specialRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialRegistration(String value) {
        this.specialRegistration = value;
    }

    /**
     * Gets the value of the stateCountryPrimaryUse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateCountryPrimaryUse() {
        return stateCountryPrimaryUse;
    }

    /**
     * Sets the value of the stateCountryPrimaryUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateCountryPrimaryUse(String value) {
        this.stateCountryPrimaryUse = value;
    }

    /**
     * Gets the value of the statePurchasedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatePurchasedIn() {
        return statePurchasedIn;
    }

    /**
     * Sets the value of the statePurchasedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatePurchasedIn(String value) {
        this.statePurchasedIn = value;
    }

    /**
     * Gets the value of the storageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageLocation() {
        return storageLocation;
    }

    /**
     * Sets the value of the storageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageLocation(String value) {
        this.storageLocation = value;
    }

    /**
     * Gets the value of the tagNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTagNumber() {
        return tagNumber;
    }

    /**
     * Sets the value of the tagNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTagNumber(String value) {
        this.tagNumber = value;
    }

    /**
     * Gets the value of the taxOne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxOne() {
        return taxOne;
    }

    /**
     * Sets the value of the taxOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxOne(String value) {
        this.taxOne = value;
    }

    /**
     * Gets the value of the titleId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleId() {
        return titleId;
    }

    /**
     * Sets the value of the titleId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleId(String value) {
        this.titleId = value;
    }

    /**
     * Gets the value of the titleStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitleStatus() {
        return titleStatus;
    }

    /**
     * Sets the value of the titleStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitleStatus(String value) {
        this.titleStatus = value;
    }

    /**
     * Gets the value of the typeOfVehicle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeOfVehicle() {
        return typeOfVehicle;
    }

    /**
     * Sets the value of the typeOfVehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeOfVehicle(String value) {
        this.typeOfVehicle = value;
    }

    /**
     * Gets the value of the uscgId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUscgId() {
        return uscgId;
    }

    /**
     * Sets the value of the uscgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUscgId(String value) {
        this.uscgId = value;
    }

    /**
     * Gets the value of the uscgRegistry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUscgRegistry() {
        return uscgRegistry;
    }

    /**
     * Sets the value of the uscgRegistry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUscgRegistry(String value) {
        this.uscgRegistry = value;
    }

    /**
     * Gets the value of the uscgTradeInd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUscgTradeInd() {
        return uscgTradeInd;
    }

    /**
     * Sets the value of the uscgTradeInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUscgTradeInd(String value) {
        this.uscgTradeInd = value;
    }

    /**
     * Gets the value of the vehDepth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehDepth() {
        return vehDepth;
    }

    /**
     * Sets the value of the vehDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehDepth(String value) {
        this.vehDepth = value;
    }

    /**
     * Gets the value of the vesselType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVesselType() {
        return vesselType;
    }

    /**
     * Sets the value of the vesselType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVesselType(String value) {
        this.vesselType = value;
    }

    /**
     * Gets the value of the weightLbs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightLbs() {
        return weightLbs;
    }

    /**
     * Sets the value of the weightLbs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightLbs(String value) {
        this.weightLbs = value;
    }

    /**
     * Gets the value of the weightTons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWeightTons() {
        return weightTons;
    }

    /**
     * Sets the value of the weightTons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWeightTons(String value) {
        this.weightTons = value;
    }

}
