//
// Generated By:JAX-WS RI IBM 2.2.1-11/28/2011 08:27 AM(foreman)- (JAXB RI IBM 2.2.3-07/05/2013 05:22 AM(foreman)-)
//


package com.acxiom.schemas.v201110.us.idod.comprehensivereport.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="APR" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CustomerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealStatus" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DealerId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExteriorColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FinancedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LaborCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NewUsed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OperationCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PaymentAmount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PostDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Recommendations" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepairOrderDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RepairOrderNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SaleType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesMan" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesMan2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesMan2Number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SalesManNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SearchId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceAdvisor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceContract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ServiceDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Term" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeAllowance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeBook" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeMake" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeMileage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradePayoff" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeStockNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TradeVIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleBodyStyle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleCost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleMake" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleMiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleModel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleSalesPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleStockNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleStore" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vehicleTradeYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleVIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VehicleYear" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyExpirationMiles" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyTermMonths" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WarrantyType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IndividualId" type="{http://schemas.acxiom.com/v201110/us/idod/common}IndividualIDType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VehicleType", propOrder = {
    "apr",
    "customerId",
    "dealDate",
    "dealId",
    "dealStatus",
    "dealerId",
    "deliveryDate",
    "exteriorColor",
    "financedBy",
    "laborCode",
    "newUsed",
    "operationCode",
    "paymentAmount",
    "postDate",
    "recommendations",
    "repairOrderDate",
    "repairOrderNumber",
    "saleType",
    "salesMan",
    "salesMan2",
    "salesMan2Number",
    "salesManNumber",
    "searchId",
    "serviceAdvisor",
    "serviceContract",
    "serviceDescription",
    "term",
    "tradeAllowance",
    "tradeBook",
    "tradeColor",
    "tradeMake",
    "tradeMileage",
    "tradeModel",
    "tradePayoff",
    "tradeStockNumber",
    "tradeVIN",
    "vehicleBodyStyle",
    "vehicleCost",
    "vehicleMake",
    "vehicleMiles",
    "vehicleModel",
    "vehicleSalesPrice",
    "vehicleStockNumber",
    "vehicleStore",
    "vehicleTradeYear",
    "vehicleVIN",
    "vehicleYear",
    "warrantyExpirationDate",
    "warrantyExpirationMiles",
    "warrantyName",
    "warrantyPrice",
    "warrantyTermMonths",
    "warrantyType",
    "individualId"
})
public class VehicleType {

    @XmlElement(name = "APR")
    protected String apr;
    @XmlElement(name = "CustomerId")
    protected String customerId;
    @XmlElement(name = "DealDate")
    protected String dealDate;
    @XmlElement(name = "DealId")
    protected String dealId;
    @XmlElement(name = "DealStatus")
    protected String dealStatus;
    @XmlElement(name = "DealerId")
    protected String dealerId;
    @XmlElement(name = "DeliveryDate")
    protected String deliveryDate;
    @XmlElement(name = "ExteriorColor")
    protected String exteriorColor;
    @XmlElement(name = "FinancedBy")
    protected String financedBy;
    @XmlElement(name = "LaborCode")
    protected String laborCode;
    @XmlElement(name = "NewUsed")
    protected String newUsed;
    @XmlElement(name = "OperationCode")
    protected String operationCode;
    @XmlElement(name = "PaymentAmount")
    protected String paymentAmount;
    @XmlElement(name = "PostDate")
    protected String postDate;
    @XmlElement(name = "Recommendations")
    protected String recommendations;
    @XmlElement(name = "RepairOrderDate")
    protected String repairOrderDate;
    @XmlElement(name = "RepairOrderNumber")
    protected String repairOrderNumber;
    @XmlElement(name = "SaleType")
    protected String saleType;
    @XmlElement(name = "SalesMan")
    protected String salesMan;
    @XmlElement(name = "SalesMan2")
    protected String salesMan2;
    @XmlElement(name = "SalesMan2Number")
    protected String salesMan2Number;
    @XmlElement(name = "SalesManNumber")
    protected String salesManNumber;
    @XmlElement(name = "SearchId")
    protected String searchId;
    @XmlElement(name = "ServiceAdvisor")
    protected String serviceAdvisor;
    @XmlElement(name = "ServiceContract")
    protected String serviceContract;
    @XmlElement(name = "ServiceDescription")
    protected String serviceDescription;
    @XmlElement(name = "Term")
    protected String term;
    @XmlElement(name = "TradeAllowance")
    protected String tradeAllowance;
    @XmlElement(name = "TradeBook")
    protected String tradeBook;
    @XmlElement(name = "TradeColor")
    protected String tradeColor;
    @XmlElement(name = "TradeMake")
    protected String tradeMake;
    @XmlElement(name = "TradeMileage")
    protected String tradeMileage;
    @XmlElement(name = "TradeModel")
    protected String tradeModel;
    @XmlElement(name = "TradePayoff")
    protected String tradePayoff;
    @XmlElement(name = "TradeStockNumber")
    protected String tradeStockNumber;
    @XmlElement(name = "TradeVIN")
    protected String tradeVIN;
    @XmlElement(name = "VehicleBodyStyle")
    protected String vehicleBodyStyle;
    @XmlElement(name = "VehicleCost")
    protected String vehicleCost;
    @XmlElement(name = "VehicleMake")
    protected String vehicleMake;
    @XmlElement(name = "VehicleMiles")
    protected String vehicleMiles;
    @XmlElement(name = "VehicleModel")
    protected String vehicleModel;
    @XmlElement(name = "VehicleSalesPrice")
    protected String vehicleSalesPrice;
    @XmlElement(name = "VehicleStockNumber")
    protected String vehicleStockNumber;
    @XmlElement(name = "VehicleStore")
    protected String vehicleStore;
    protected String vehicleTradeYear;
    @XmlElement(name = "VehicleVIN")
    protected String vehicleVIN;
    @XmlElement(name = "VehicleYear")
    protected String vehicleYear;
    @XmlElement(name = "WarrantyExpirationDate")
    protected String warrantyExpirationDate;
    @XmlElement(name = "WarrantyExpirationMiles")
    protected String warrantyExpirationMiles;
    @XmlElement(name = "WarrantyName")
    protected String warrantyName;
    @XmlElement(name = "WarrantyPrice")
    protected String warrantyPrice;
    @XmlElement(name = "WarrantyTermMonths")
    protected String warrantyTermMonths;
    @XmlElement(name = "WarrantyType")
    protected String warrantyType;
    @XmlElement(name = "IndividualId")
    protected String individualId;

    /**
     * Gets the value of the apr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAPR() {
        return apr;
    }

    /**
     * Sets the value of the apr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAPR(String value) {
        this.apr = value;
    }

    /**
     * Gets the value of the customerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * Sets the value of the customerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerId(String value) {
        this.customerId = value;
    }

    /**
     * Gets the value of the dealDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealDate() {
        return dealDate;
    }

    /**
     * Sets the value of the dealDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealDate(String value) {
        this.dealDate = value;
    }

    /**
     * Gets the value of the dealId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealId() {
        return dealId;
    }

    /**
     * Sets the value of the dealId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealId(String value) {
        this.dealId = value;
    }

    /**
     * Gets the value of the dealStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealStatus() {
        return dealStatus;
    }

    /**
     * Sets the value of the dealStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealStatus(String value) {
        this.dealStatus = value;
    }

    /**
     * Gets the value of the dealerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDealerId() {
        return dealerId;
    }

    /**
     * Sets the value of the dealerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDealerId(String value) {
        this.dealerId = value;
    }

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryDate(String value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the exteriorColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExteriorColor() {
        return exteriorColor;
    }

    /**
     * Sets the value of the exteriorColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExteriorColor(String value) {
        this.exteriorColor = value;
    }

    /**
     * Gets the value of the financedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFinancedBy() {
        return financedBy;
    }

    /**
     * Sets the value of the financedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFinancedBy(String value) {
        this.financedBy = value;
    }

    /**
     * Gets the value of the laborCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLaborCode() {
        return laborCode;
    }

    /**
     * Sets the value of the laborCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLaborCode(String value) {
        this.laborCode = value;
    }

    /**
     * Gets the value of the newUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewUsed() {
        return newUsed;
    }

    /**
     * Sets the value of the newUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewUsed(String value) {
        this.newUsed = value;
    }

    /**
     * Gets the value of the operationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperationCode() {
        return operationCode;
    }

    /**
     * Sets the value of the operationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationCode(String value) {
        this.operationCode = value;
    }

    /**
     * Gets the value of the paymentAmount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentAmount() {
        return paymentAmount;
    }

    /**
     * Sets the value of the paymentAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentAmount(String value) {
        this.paymentAmount = value;
    }

    /**
     * Gets the value of the postDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostDate() {
        return postDate;
    }

    /**
     * Sets the value of the postDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostDate(String value) {
        this.postDate = value;
    }

    /**
     * Gets the value of the recommendations property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendations() {
        return recommendations;
    }

    /**
     * Sets the value of the recommendations property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendations(String value) {
        this.recommendations = value;
    }

    /**
     * Gets the value of the repairOrderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairOrderDate() {
        return repairOrderDate;
    }

    /**
     * Sets the value of the repairOrderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairOrderDate(String value) {
        this.repairOrderDate = value;
    }

    /**
     * Gets the value of the repairOrderNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepairOrderNumber() {
        return repairOrderNumber;
    }

    /**
     * Sets the value of the repairOrderNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepairOrderNumber(String value) {
        this.repairOrderNumber = value;
    }

    /**
     * Gets the value of the saleType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSaleType() {
        return saleType;
    }

    /**
     * Sets the value of the saleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSaleType(String value) {
        this.saleType = value;
    }

    /**
     * Gets the value of the salesMan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesMan() {
        return salesMan;
    }

    /**
     * Sets the value of the salesMan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesMan(String value) {
        this.salesMan = value;
    }

    /**
     * Gets the value of the salesMan2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesMan2() {
        return salesMan2;
    }

    /**
     * Sets the value of the salesMan2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesMan2(String value) {
        this.salesMan2 = value;
    }

    /**
     * Gets the value of the salesMan2Number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesMan2Number() {
        return salesMan2Number;
    }

    /**
     * Sets the value of the salesMan2Number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesMan2Number(String value) {
        this.salesMan2Number = value;
    }

    /**
     * Gets the value of the salesManNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSalesManNumber() {
        return salesManNumber;
    }

    /**
     * Sets the value of the salesManNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSalesManNumber(String value) {
        this.salesManNumber = value;
    }

    /**
     * Gets the value of the searchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchId() {
        return searchId;
    }

    /**
     * Sets the value of the searchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchId(String value) {
        this.searchId = value;
    }

    /**
     * Gets the value of the serviceAdvisor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceAdvisor() {
        return serviceAdvisor;
    }

    /**
     * Sets the value of the serviceAdvisor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceAdvisor(String value) {
        this.serviceAdvisor = value;
    }

    /**
     * Gets the value of the serviceContract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceContract() {
        return serviceContract;
    }

    /**
     * Sets the value of the serviceContract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceContract(String value) {
        this.serviceContract = value;
    }

    /**
     * Gets the value of the serviceDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceDescription() {
        return serviceDescription;
    }

    /**
     * Sets the value of the serviceDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceDescription(String value) {
        this.serviceDescription = value;
    }

    /**
     * Gets the value of the term property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTerm() {
        return term;
    }

    /**
     * Sets the value of the term property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTerm(String value) {
        this.term = value;
    }

    /**
     * Gets the value of the tradeAllowance property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeAllowance() {
        return tradeAllowance;
    }

    /**
     * Sets the value of the tradeAllowance property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeAllowance(String value) {
        this.tradeAllowance = value;
    }

    /**
     * Gets the value of the tradeBook property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeBook() {
        return tradeBook;
    }

    /**
     * Sets the value of the tradeBook property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeBook(String value) {
        this.tradeBook = value;
    }

    /**
     * Gets the value of the tradeColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeColor() {
        return tradeColor;
    }

    /**
     * Sets the value of the tradeColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeColor(String value) {
        this.tradeColor = value;
    }

    /**
     * Gets the value of the tradeMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMake() {
        return tradeMake;
    }

    /**
     * Sets the value of the tradeMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMake(String value) {
        this.tradeMake = value;
    }

    /**
     * Gets the value of the tradeMileage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMileage() {
        return tradeMileage;
    }

    /**
     * Sets the value of the tradeMileage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMileage(String value) {
        this.tradeMileage = value;
    }

    /**
     * Gets the value of the tradeModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeModel() {
        return tradeModel;
    }

    /**
     * Sets the value of the tradeModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeModel(String value) {
        this.tradeModel = value;
    }

    /**
     * Gets the value of the tradePayoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradePayoff() {
        return tradePayoff;
    }

    /**
     * Sets the value of the tradePayoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradePayoff(String value) {
        this.tradePayoff = value;
    }

    /**
     * Gets the value of the tradeStockNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeStockNumber() {
        return tradeStockNumber;
    }

    /**
     * Sets the value of the tradeStockNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeStockNumber(String value) {
        this.tradeStockNumber = value;
    }

    /**
     * Gets the value of the tradeVIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeVIN() {
        return tradeVIN;
    }

    /**
     * Sets the value of the tradeVIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeVIN(String value) {
        this.tradeVIN = value;
    }

    /**
     * Gets the value of the vehicleBodyStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleBodyStyle() {
        return vehicleBodyStyle;
    }

    /**
     * Sets the value of the vehicleBodyStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleBodyStyle(String value) {
        this.vehicleBodyStyle = value;
    }

    /**
     * Gets the value of the vehicleCost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleCost() {
        return vehicleCost;
    }

    /**
     * Sets the value of the vehicleCost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleCost(String value) {
        this.vehicleCost = value;
    }

    /**
     * Gets the value of the vehicleMake property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMake() {
        return vehicleMake;
    }

    /**
     * Sets the value of the vehicleMake property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMake(String value) {
        this.vehicleMake = value;
    }

    /**
     * Gets the value of the vehicleMiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleMiles() {
        return vehicleMiles;
    }

    /**
     * Sets the value of the vehicleMiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleMiles(String value) {
        this.vehicleMiles = value;
    }

    /**
     * Gets the value of the vehicleModel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleModel() {
        return vehicleModel;
    }

    /**
     * Sets the value of the vehicleModel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleModel(String value) {
        this.vehicleModel = value;
    }

    /**
     * Gets the value of the vehicleSalesPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleSalesPrice() {
        return vehicleSalesPrice;
    }

    /**
     * Sets the value of the vehicleSalesPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleSalesPrice(String value) {
        this.vehicleSalesPrice = value;
    }

    /**
     * Gets the value of the vehicleStockNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleStockNumber() {
        return vehicleStockNumber;
    }

    /**
     * Sets the value of the vehicleStockNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleStockNumber(String value) {
        this.vehicleStockNumber = value;
    }

    /**
     * Gets the value of the vehicleStore property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleStore() {
        return vehicleStore;
    }

    /**
     * Sets the value of the vehicleStore property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleStore(String value) {
        this.vehicleStore = value;
    }

    /**
     * Gets the value of the vehicleTradeYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleTradeYear() {
        return vehicleTradeYear;
    }

    /**
     * Sets the value of the vehicleTradeYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleTradeYear(String value) {
        this.vehicleTradeYear = value;
    }

    /**
     * Gets the value of the vehicleVIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleVIN() {
        return vehicleVIN;
    }

    /**
     * Sets the value of the vehicleVIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleVIN(String value) {
        this.vehicleVIN = value;
    }

    /**
     * Gets the value of the vehicleYear property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVehicleYear() {
        return vehicleYear;
    }

    /**
     * Sets the value of the vehicleYear property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVehicleYear(String value) {
        this.vehicleYear = value;
    }

    /**
     * Gets the value of the warrantyExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyExpirationDate() {
        return warrantyExpirationDate;
    }

    /**
     * Sets the value of the warrantyExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyExpirationDate(String value) {
        this.warrantyExpirationDate = value;
    }

    /**
     * Gets the value of the warrantyExpirationMiles property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyExpirationMiles() {
        return warrantyExpirationMiles;
    }

    /**
     * Sets the value of the warrantyExpirationMiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyExpirationMiles(String value) {
        this.warrantyExpirationMiles = value;
    }

    /**
     * Gets the value of the warrantyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyName() {
        return warrantyName;
    }

    /**
     * Sets the value of the warrantyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyName(String value) {
        this.warrantyName = value;
    }

    /**
     * Gets the value of the warrantyPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyPrice() {
        return warrantyPrice;
    }

    /**
     * Sets the value of the warrantyPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyPrice(String value) {
        this.warrantyPrice = value;
    }

    /**
     * Gets the value of the warrantyTermMonths property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyTermMonths() {
        return warrantyTermMonths;
    }

    /**
     * Sets the value of the warrantyTermMonths property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyTermMonths(String value) {
        this.warrantyTermMonths = value;
    }

    /**
     * Gets the value of the warrantyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWarrantyType() {
        return warrantyType;
    }

    /**
     * Sets the value of the warrantyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWarrantyType(String value) {
        this.warrantyType = value;
    }

    /**
     * Gets the value of the individualId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndividualId() {
        return individualId;
    }

    /**
     * Sets the value of the individualId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndividualId(String value) {
        this.individualId = value;
    }

}
